// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: assignment_reference_service.proto

package assignment_reference_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PageSize          int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ActiveOnly        *bool                  `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3,oneof" json:"active_only,omitempty"`
	FilterDisplayName *string                `protobuf:"bytes,4,opt,name=filter_display_name,json=filterDisplayName,proto3,oneof" json:"filter_display_name,omitempty"`
	FilterUsername    *string                `protobuf:"bytes,5,opt,name=filter_username,json=filterUsername,proto3,oneof" json:"filter_username,omitempty"`
	FilterEmail       *string                `protobuf:"bytes,6,opt,name=filter_email,json=filterEmail,proto3,oneof" json:"filter_email,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetActiveOnly() bool {
	if x != nil && x.ActiveOnly != nil {
		return *x.ActiveOnly
	}
	return false
}

func (x *ListUsersRequest) GetFilterDisplayName() string {
	if x != nil && x.FilterDisplayName != nil {
		return *x.FilterDisplayName
	}
	return ""
}

func (x *ListUsersRequest) GetFilterUsername() string {
	if x != nil && x.FilterUsername != nil {
		return *x.FilterUsername
	}
	return ""
}

func (x *ListUsersRequest) GetFilterEmail() string {
	if x != nil && x.FilterEmail != nil {
		return *x.FilterEmail
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*User                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type ListGroupsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageSize        int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ActiveOnly      *bool                  `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3,oneof" json:"active_only,omitempty"`
	FilterGroupName *string                `protobuf:"bytes,4,opt,name=filter_group_name,json=filterGroupName,proto3,oneof" json:"filter_group_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListGroupsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGroupsRequest) GetActiveOnly() bool {
	if x != nil && x.ActiveOnly != nil {
		return *x.ActiveOnly
	}
	return false
}

func (x *ListGroupsRequest) GetFilterGroupName() string {
	if x != nil && x.FilterGroupName != nil {
		return *x.FilterGroupName
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Group               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListGroupsResponse) GetItems() []*Group {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListGroupMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupMembersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListGroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GroupMember         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersResponse) Reset() {
	*x = ListGroupMembersResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse) ProtoMessage() {}

func (x *ListGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupMembersResponse) GetItems() []*GroupMember {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListGroupMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ValidateUserExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserExistsRequest) Reset() {
	*x = ValidateUserExistsRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserExistsRequest) ProtoMessage() {}

func (x *ValidateUserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserExistsRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserExistsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateUserExistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ValidateUserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserExistsResponse) Reset() {
	*x = ValidateUserExistsResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserExistsResponse) ProtoMessage() {}

func (x *ValidateUserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserExistsResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserExistsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateUserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ValidateGroupExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGroupExistsRequest) Reset() {
	*x = ValidateGroupExistsRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGroupExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGroupExistsRequest) ProtoMessage() {}

func (x *ValidateGroupExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGroupExistsRequest.ProtoReflect.Descriptor instead.
func (*ValidateGroupExistsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateGroupExistsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ValidateGroupExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGroupExistsResponse) Reset() {
	*x = ValidateGroupExistsResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGroupExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGroupExistsResponse) ProtoMessage() {}

func (x *ValidateGroupExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGroupExistsResponse.ProtoReflect.Descriptor instead.
func (*ValidateGroupExistsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateGroupExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	DisplayName   *string                `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	IsActive      *bool                  `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{19}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName     *string                `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3,oneof" json:"group_name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsActive      *bool                  `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetGroupName() string {
	if x != nil && x.GroupName != nil {
		return *x.GroupName
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type AddGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberRole    string                 `protobuf:"bytes,3,opt,name=member_role,json=memberRole,proto3" json:"member_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupMemberRequest) Reset() {
	*x = AddGroupMemberRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMemberRequest) ProtoMessage() {}

func (x *AddGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*AddGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{22}
}

func (x *AddGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddGroupMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddGroupMemberRequest) GetMemberRole() string {
	if x != nil {
		return x.MemberRole
	}
	return ""
}

type AddGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *GroupMember           `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupMemberResponse) Reset() {
	*x = AddGroupMemberResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMemberResponse) ProtoMessage() {}

func (x *AddGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*AddGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{23}
}

func (x *AddGroupMemberResponse) GetMember() *GroupMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberRequest) Reset() {
	*x = RemoveGroupMemberRequest{}
	mi := &file_assignment_reference_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRequest) ProtoMessage() {}

func (x *RemoveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveGroupMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberResponse) Reset() {
	*x = RemoveGroupMemberResponse{}
	mi := &file_assignment_reference_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberResponse) ProtoMessage() {}

func (x *RemoveGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{25}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_assignment_reference_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{26}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_assignment_reference_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{27}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberRole    string                 `protobuf:"bytes,4,opt,name=member_role,json=memberRole,proto3" json:"member_role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_assignment_reference_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_reference_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_assignment_reference_service_proto_rawDescGZIP(), []int{28}
}

func (x *GroupMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupMember) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMember) GetMemberRole() string {
	if x != nil {
		return x.MemberRole
	}
	return ""
}

func (x *GroupMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_assignment_reference_service_proto protoreflect.FileDescriptor

const file_assignment_reference_service_proto_rawDesc = "" +
	"\n" +
	"\"assignment_reference_service.proto\x12\x1cassignment_reference_service\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x0fGetUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".assignment_reference_service.UserR\x04user\"\xcc\x02\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12$\n" +
	"\vactive_only\x18\x03 \x01(\bH\x00R\n" +
	"activeOnly\x88\x01\x01\x123\n" +
	"\x13filter_display_name\x18\x04 \x01(\tH\x01R\x11filterDisplayName\x88\x01\x01\x12,\n" +
	"\x0ffilter_username\x18\x05 \x01(\tH\x02R\x0efilterUsername\x88\x01\x01\x12&\n" +
	"\ffilter_email\x18\x06 \x01(\tH\x03R\vfilterEmail\x88\x01\x01B\x0e\n" +
	"\f_active_onlyB\x16\n" +
	"\x14_filter_display_nameB\x12\n" +
	"\x10_filter_usernameB\x0f\n" +
	"\r_filter_email\"u\n" +
	"\x11ListUsersResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".assignment_reference_service.UserR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x10GetGroupResponse\x129\n" +
	"\x05group\x18\x01 \x01(\v2#.assignment_reference_service.GroupR\x05group\"\xcc\x01\n" +
	"\x11ListGroupsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12$\n" +
	"\vactive_only\x18\x03 \x01(\bH\x00R\n" +
	"activeOnly\x88\x01\x01\x12/\n" +
	"\x11filter_group_name\x18\x04 \x01(\tH\x01R\x0ffilterGroupName\x88\x01\x01B\x0e\n" +
	"\f_active_onlyB\x14\n" +
	"\x12_filter_group_name\"w\n" +
	"\x12ListGroupsResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.assignment_reference_service.GroupR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"p\n" +
	"\x17ListGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x18ListGroupMembersResponse\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).assignment_reference_service.GroupMemberR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"4\n" +
	"\x19ValidateUserExistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x1aValidateUserExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"7\n" +
	"\x1aValidateGroupExistsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"5\n" +
	"\x1bValidateGroupExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x85\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"L\n" +
	"\x12CreateUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".assignment_reference_service.UserR\x04user\"\xdf\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tH\x02R\vdisplayName\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x05 \x01(\bH\x03R\bisActive\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_display_nameB\f\n" +
	"\n" +
	"_is_active\"L\n" +
	"\x12UpdateUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".assignment_reference_service.UserR\x04user\"r\n" +
	"\x12CreateGroupRequest\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"P\n" +
	"\x13CreateGroupResponse\x129\n" +
	"\x05group\x18\x01 \x01(\v2#.assignment_reference_service.GroupR\x05group\"\xbe\x01\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tH\x00R\tgroupName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x04 \x01(\bH\x02R\bisActive\x88\x01\x01B\r\n" +
	"\v_group_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_is_active\"P\n" +
	"\x13UpdateGroupResponse\x129\n" +
	"\x05group\x18\x01 \x01(\v2#.assignment_reference_service.GroupR\x05group\"l\n" +
	"\x15AddGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmember_role\x18\x03 \x01(\tR\n" +
	"memberRole\"[\n" +
	"\x16AddGroupMemberResponse\x12A\n" +
	"\x06member\x18\x01 \x01(\v2).assignment_reference_service.GroupMemberR\x06member\"N\n" +
	"\x18RemoveGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1b\n" +
	"\x19RemoveGroupMemberResponse\"\xfe\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xeb\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xad\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmember_role\x18\x04 \x01(\tR\n" +
	"memberRole\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xb7\f\n" +
	"\x1aAssignmentReferenceService\x12f\n" +
	"\aGetUser\x12,.assignment_reference_service.GetUserRequest\x1a-.assignment_reference_service.GetUserResponse\x12l\n" +
	"\tListUsers\x12..assignment_reference_service.ListUsersRequest\x1a/.assignment_reference_service.ListUsersResponse\x12i\n" +
	"\bGetGroup\x12-.assignment_reference_service.GetGroupRequest\x1a..assignment_reference_service.GetGroupResponse\x12o\n" +
	"\n" +
	"ListGroups\x12/.assignment_reference_service.ListGroupsRequest\x1a0.assignment_reference_service.ListGroupsResponse\x12\x81\x01\n" +
	"\x10ListGroupMembers\x125.assignment_reference_service.ListGroupMembersRequest\x1a6.assignment_reference_service.ListGroupMembersResponse\x12\x87\x01\n" +
	"\x12ValidateUserExists\x127.assignment_reference_service.ValidateUserExistsRequest\x1a8.assignment_reference_service.ValidateUserExistsResponse\x12\x8a\x01\n" +
	"\x13ValidateGroupExists\x128.assignment_reference_service.ValidateGroupExistsRequest\x1a9.assignment_reference_service.ValidateGroupExistsResponse\x12o\n" +
	"\n" +
	"CreateUser\x12/.assignment_reference_service.CreateUserRequest\x1a0.assignment_reference_service.CreateUserResponse\x12o\n" +
	"\n" +
	"UpdateUser\x12/.assignment_reference_service.UpdateUserRequest\x1a0.assignment_reference_service.UpdateUserResponse\x12r\n" +
	"\vCreateGroup\x120.assignment_reference_service.CreateGroupRequest\x1a1.assignment_reference_service.CreateGroupResponse\x12r\n" +
	"\vUpdateGroup\x120.assignment_reference_service.UpdateGroupRequest\x1a1.assignment_reference_service.UpdateGroupResponse\x12{\n" +
	"\x0eAddGroupMember\x123.assignment_reference_service.AddGroupMemberRequest\x1a4.assignment_reference_service.AddGroupMemberResponse\x12\x84\x01\n" +
	"\x11RemoveGroupMember\x126.assignment_reference_service.RemoveGroupMemberRequest\x1a7.assignment_reference_service.RemoveGroupMemberResponseBWZUgithub.com/servicenow/assignment-reference-service/proto/assignment_reference_serviceb\x06proto3"

var (
	file_assignment_reference_service_proto_rawDescOnce sync.Once
	file_assignment_reference_service_proto_rawDescData []byte
)

func file_assignment_reference_service_proto_rawDescGZIP() []byte {
	file_assignment_reference_service_proto_rawDescOnce.Do(func() {
		file_assignment_reference_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assignment_reference_service_proto_rawDesc), len(file_assignment_reference_service_proto_rawDesc)))
	})
	return file_assignment_reference_service_proto_rawDescData
}

var file_assignment_reference_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_assignment_reference_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),              // 0: assignment_reference_service.GetUserRequest
	(*GetUserResponse)(nil),             // 1: assignment_reference_service.GetUserResponse
	(*ListUsersRequest)(nil),            // 2: assignment_reference_service.ListUsersRequest
	(*ListUsersResponse)(nil),           // 3: assignment_reference_service.ListUsersResponse
	(*GetGroupRequest)(nil),             // 4: assignment_reference_service.GetGroupRequest
	(*GetGroupResponse)(nil),            // 5: assignment_reference_service.GetGroupResponse
	(*ListGroupsRequest)(nil),           // 6: assignment_reference_service.ListGroupsRequest
	(*ListGroupsResponse)(nil),          // 7: assignment_reference_service.ListGroupsResponse
	(*ListGroupMembersRequest)(nil),     // 8: assignment_reference_service.ListGroupMembersRequest
	(*ListGroupMembersResponse)(nil),    // 9: assignment_reference_service.ListGroupMembersResponse
	(*ValidateUserExistsRequest)(nil),   // 10: assignment_reference_service.ValidateUserExistsRequest
	(*ValidateUserExistsResponse)(nil),  // 11: assignment_reference_service.ValidateUserExistsResponse
	(*ValidateGroupExistsRequest)(nil),  // 12: assignment_reference_service.ValidateGroupExistsRequest
	(*ValidateGroupExistsResponse)(nil), // 13: assignment_reference_service.ValidateGroupExistsResponse
	(*CreateUserRequest)(nil),           // 14: assignment_reference_service.CreateUserRequest
	(*CreateUserResponse)(nil),          // 15: assignment_reference_service.CreateUserResponse
	(*UpdateUserRequest)(nil),           // 16: assignment_reference_service.UpdateUserRequest
	(*UpdateUserResponse)(nil),          // 17: assignment_reference_service.UpdateUserResponse
	(*CreateGroupRequest)(nil),          // 18: assignment_reference_service.CreateGroupRequest
	(*CreateGroupResponse)(nil),         // 19: assignment_reference_service.CreateGroupResponse
	(*UpdateGroupRequest)(nil),          // 20: assignment_reference_service.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),         // 21: assignment_reference_service.UpdateGroupResponse
	(*AddGroupMemberRequest)(nil),       // 22: assignment_reference_service.AddGroupMemberRequest
	(*AddGroupMemberResponse)(nil),      // 23: assignment_reference_service.AddGroupMemberResponse
	(*RemoveGroupMemberRequest)(nil),    // 24: assignment_reference_service.RemoveGroupMemberRequest
	(*RemoveGroupMemberResponse)(nil),   // 25: assignment_reference_service.RemoveGroupMemberResponse
	(*User)(nil),                        // 26: assignment_reference_service.User
	(*Group)(nil),                       // 27: assignment_reference_service.Group
	(*GroupMember)(nil),                 // 28: assignment_reference_service.GroupMember
	(*timestamppb.Timestamp)(nil),       // 29: google.protobuf.Timestamp
}
var file_assignment_reference_service_proto_depIdxs = []int32{
	26, // 0: assignment_reference_service.GetUserResponse.user:type_name -> assignment_reference_service.User
	26, // 1: assignment_reference_service.ListUsersResponse.items:type_name -> assignment_reference_service.User
	27, // 2: assignment_reference_service.GetGroupResponse.group:type_name -> assignment_reference_service.Group
	27, // 3: assignment_reference_service.ListGroupsResponse.items:type_name -> assignment_reference_service.Group
	28, // 4: assignment_reference_service.ListGroupMembersResponse.items:type_name -> assignment_reference_service.GroupMember
	26, // 5: assignment_reference_service.CreateUserResponse.user:type_name -> assignment_reference_service.User
	26, // 6: assignment_reference_service.UpdateUserResponse.user:type_name -> assignment_reference_service.User
	27, // 7: assignment_reference_service.CreateGroupResponse.group:type_name -> assignment_reference_service.Group
	27, // 8: assignment_reference_service.UpdateGroupResponse.group:type_name -> assignment_reference_service.Group
	28, // 9: assignment_reference_service.AddGroupMemberResponse.member:type_name -> assignment_reference_service.GroupMember
	29, // 10: assignment_reference_service.User.created_at:type_name -> google.protobuf.Timestamp
	29, // 11: assignment_reference_service.User.updated_at:type_name -> google.protobuf.Timestamp
	29, // 12: assignment_reference_service.Group.created_at:type_name -> google.protobuf.Timestamp
	29, // 13: assignment_reference_service.Group.updated_at:type_name -> google.protobuf.Timestamp
	29, // 14: assignment_reference_service.GroupMember.created_at:type_name -> google.protobuf.Timestamp
	0,  // 15: assignment_reference_service.AssignmentReferenceService.GetUser:input_type -> assignment_reference_service.GetUserRequest
	2,  // 16: assignment_reference_service.AssignmentReferenceService.ListUsers:input_type -> assignment_reference_service.ListUsersRequest
	4,  // 17: assignment_reference_service.AssignmentReferenceService.GetGroup:input_type -> assignment_reference_service.GetGroupRequest
	6,  // 18: assignment_reference_service.AssignmentReferenceService.ListGroups:input_type -> assignment_reference_service.ListGroupsRequest
	8,  // 19: assignment_reference_service.AssignmentReferenceService.ListGroupMembers:input_type -> assignment_reference_service.ListGroupMembersRequest
	10, // 20: assignment_reference_service.AssignmentReferenceService.ValidateUserExists:input_type -> assignment_reference_service.ValidateUserExistsRequest
	12, // 21: assignment_reference_service.AssignmentReferenceService.ValidateGroupExists:input_type -> assignment_reference_service.ValidateGroupExistsRequest
	14, // 22: assignment_reference_service.AssignmentReferenceService.CreateUser:input_type -> assignment_reference_service.CreateUserRequest
	16, // 23: assignment_reference_service.AssignmentReferenceService.UpdateUser:input_type -> assignment_reference_service.UpdateUserRequest
	18, // 24: assignment_reference_service.AssignmentReferenceService.CreateGroup:input_type -> assignment_reference_service.CreateGroupRequest
	20, // 25: assignment_reference_service.AssignmentReferenceService.UpdateGroup:input_type -> assignment_reference_service.UpdateGroupRequest
	22, // 26: assignment_reference_service.AssignmentReferenceService.AddGroupMember:input_type -> assignment_reference_service.AddGroupMemberRequest
	24, // 27: assignment_reference_service.AssignmentReferenceService.RemoveGroupMember:input_type -> assignment_reference_service.RemoveGroupMemberRequest
	1,  // 28: assignment_reference_service.AssignmentReferenceService.GetUser:output_type -> assignment_reference_service.GetUserResponse
	3,  // 29: assignment_reference_service.AssignmentReferenceService.ListUsers:output_type -> assignment_reference_service.ListUsersResponse
	5,  // 30: assignment_reference_service.AssignmentReferenceService.GetGroup:output_type -> assignment_reference_service.GetGroupResponse
	7,  // 31: assignment_reference_service.AssignmentReferenceService.ListGroups:output_type -> assignment_reference_service.ListGroupsResponse
	9,  // 32: assignment_reference_service.AssignmentReferenceService.ListGroupMembers:output_type -> assignment_reference_service.ListGroupMembersResponse
	11, // 33: assignment_reference_service.AssignmentReferenceService.ValidateUserExists:output_type -> assignment_reference_service.ValidateUserExistsResponse
	13, // 34: assignment_reference_service.AssignmentReferenceService.ValidateGroupExists:output_type -> assignment_reference_service.ValidateGroupExistsResponse
	15, // 35: assignment_reference_service.AssignmentReferenceService.CreateUser:output_type -> assignment_reference_service.CreateUserResponse
	17, // 36: assignment_reference_service.AssignmentReferenceService.UpdateUser:output_type -> assignment_reference_service.UpdateUserResponse
	19, // 37: assignment_reference_service.AssignmentReferenceService.CreateGroup:output_type -> assignment_reference_service.CreateGroupResponse
	21, // 38: assignment_reference_service.AssignmentReferenceService.UpdateGroup:output_type -> assignment_reference_service.UpdateGroupResponse
	23, // 39: assignment_reference_service.AssignmentReferenceService.AddGroupMember:output_type -> assignment_reference_service.AddGroupMemberResponse
	25, // 40: assignment_reference_service.AssignmentReferenceService.RemoveGroupMember:output_type -> assignment_reference_service.RemoveGroupMemberResponse
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_assignment_reference_service_proto_init() }
func file_assignment_reference_service_proto_init() {
	if File_assignment_reference_service_proto != nil {
		return
	}
	file_assignment_reference_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_assignment_reference_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_assignment_reference_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_assignment_reference_service_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assignment_reference_service_proto_rawDesc), len(file_assignment_reference_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assignment_reference_service_proto_goTypes,
		DependencyIndexes: file_assignment_reference_service_proto_depIdxs,
		MessageInfos:      file_assignment_reference_service_proto_msgTypes,
	}.Build()
	File_assignment_reference_service_proto = out.File
	file_assignment_reference_service_proto_goTypes = nil
	file_assignment_reference_service_proto_depIdxs = nil
}
