// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: enrichment_threat_service.proto

package enrichment_threat_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrichmentThreatService_UpsertEnrichmentResult_FullMethodName              = "/enrichment_threat_service.EnrichmentThreatService/UpsertEnrichmentResult"
	EnrichmentThreatService_UpsertThreatLookupResult_FullMethodName            = "/enrichment_threat_service.EnrichmentThreatService/UpsertThreatLookupResult"
	EnrichmentThreatService_ListEnrichmentResultsByCase_FullMethodName         = "/enrichment_threat_service.EnrichmentThreatService/ListEnrichmentResultsByCase"
	EnrichmentThreatService_ListEnrichmentResultsByObservable_FullMethodName   = "/enrichment_threat_service.EnrichmentThreatService/ListEnrichmentResultsByObservable"
	EnrichmentThreatService_ListThreatLookupResultsByCase_FullMethodName       = "/enrichment_threat_service.EnrichmentThreatService/ListThreatLookupResultsByCase"
	EnrichmentThreatService_ListThreatLookupResultsByObservable_FullMethodName = "/enrichment_threat_service.EnrichmentThreatService/ListThreatLookupResultsByObservable"
	EnrichmentThreatService_GetThreatLookupSummaryByObservable_FullMethodName  = "/enrichment_threat_service.EnrichmentThreatService/GetThreatLookupSummaryByObservable"
)

// EnrichmentThreatServiceClient is the client API for EnrichmentThreatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrichmentThreatServiceClient interface {
	UpsertEnrichmentResult(ctx context.Context, in *UpsertEnrichmentResultRequest, opts ...grpc.CallOption) (*UpsertEnrichmentResultResponse, error)
	UpsertThreatLookupResult(ctx context.Context, in *UpsertThreatLookupResultRequest, opts ...grpc.CallOption) (*UpsertThreatLookupResultResponse, error)
	ListEnrichmentResultsByCase(ctx context.Context, in *ListEnrichmentResultsByCaseRequest, opts ...grpc.CallOption) (*ListEnrichmentResultsByCaseResponse, error)
	ListEnrichmentResultsByObservable(ctx context.Context, in *ListEnrichmentResultsByObservableRequest, opts ...grpc.CallOption) (*ListEnrichmentResultsByObservableResponse, error)
	ListThreatLookupResultsByCase(ctx context.Context, in *ListThreatLookupResultsByCaseRequest, opts ...grpc.CallOption) (*ListThreatLookupResultsByCaseResponse, error)
	ListThreatLookupResultsByObservable(ctx context.Context, in *ListThreatLookupResultsByObservableRequest, opts ...grpc.CallOption) (*ListThreatLookupResultsByObservableResponse, error)
	GetThreatLookupSummaryByObservable(ctx context.Context, in *GetThreatLookupSummaryByObservableRequest, opts ...grpc.CallOption) (*GetThreatLookupSummaryByObservableResponse, error)
}

type enrichmentThreatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrichmentThreatServiceClient(cc grpc.ClientConnInterface) EnrichmentThreatServiceClient {
	return &enrichmentThreatServiceClient{cc}
}

func (c *enrichmentThreatServiceClient) UpsertEnrichmentResult(ctx context.Context, in *UpsertEnrichmentResultRequest, opts ...grpc.CallOption) (*UpsertEnrichmentResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEnrichmentResultResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_UpsertEnrichmentResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentThreatServiceClient) UpsertThreatLookupResult(ctx context.Context, in *UpsertThreatLookupResultRequest, opts ...grpc.CallOption) (*UpsertThreatLookupResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertThreatLookupResultResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_UpsertThreatLookupResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentThreatServiceClient) ListEnrichmentResultsByCase(ctx context.Context, in *ListEnrichmentResultsByCaseRequest, opts ...grpc.CallOption) (*ListEnrichmentResultsByCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrichmentResultsByCaseResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_ListEnrichmentResultsByCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentThreatServiceClient) ListEnrichmentResultsByObservable(ctx context.Context, in *ListEnrichmentResultsByObservableRequest, opts ...grpc.CallOption) (*ListEnrichmentResultsByObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrichmentResultsByObservableResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_ListEnrichmentResultsByObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentThreatServiceClient) ListThreatLookupResultsByCase(ctx context.Context, in *ListThreatLookupResultsByCaseRequest, opts ...grpc.CallOption) (*ListThreatLookupResultsByCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListThreatLookupResultsByCaseResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_ListThreatLookupResultsByCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentThreatServiceClient) ListThreatLookupResultsByObservable(ctx context.Context, in *ListThreatLookupResultsByObservableRequest, opts ...grpc.CallOption) (*ListThreatLookupResultsByObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListThreatLookupResultsByObservableResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_ListThreatLookupResultsByObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentThreatServiceClient) GetThreatLookupSummaryByObservable(ctx context.Context, in *GetThreatLookupSummaryByObservableRequest, opts ...grpc.CallOption) (*GetThreatLookupSummaryByObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThreatLookupSummaryByObservableResponse)
	err := c.cc.Invoke(ctx, EnrichmentThreatService_GetThreatLookupSummaryByObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrichmentThreatServiceServer is the server API for EnrichmentThreatService service.
// All implementations must embed UnimplementedEnrichmentThreatServiceServer
// for forward compatibility.
type EnrichmentThreatServiceServer interface {
	UpsertEnrichmentResult(context.Context, *UpsertEnrichmentResultRequest) (*UpsertEnrichmentResultResponse, error)
	UpsertThreatLookupResult(context.Context, *UpsertThreatLookupResultRequest) (*UpsertThreatLookupResultResponse, error)
	ListEnrichmentResultsByCase(context.Context, *ListEnrichmentResultsByCaseRequest) (*ListEnrichmentResultsByCaseResponse, error)
	ListEnrichmentResultsByObservable(context.Context, *ListEnrichmentResultsByObservableRequest) (*ListEnrichmentResultsByObservableResponse, error)
	ListThreatLookupResultsByCase(context.Context, *ListThreatLookupResultsByCaseRequest) (*ListThreatLookupResultsByCaseResponse, error)
	ListThreatLookupResultsByObservable(context.Context, *ListThreatLookupResultsByObservableRequest) (*ListThreatLookupResultsByObservableResponse, error)
	GetThreatLookupSummaryByObservable(context.Context, *GetThreatLookupSummaryByObservableRequest) (*GetThreatLookupSummaryByObservableResponse, error)
	mustEmbedUnimplementedEnrichmentThreatServiceServer()
}

// UnimplementedEnrichmentThreatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrichmentThreatServiceServer struct{}

func (UnimplementedEnrichmentThreatServiceServer) UpsertEnrichmentResult(context.Context, *UpsertEnrichmentResultRequest) (*UpsertEnrichmentResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertEnrichmentResult not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) UpsertThreatLookupResult(context.Context, *UpsertThreatLookupResultRequest) (*UpsertThreatLookupResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertThreatLookupResult not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) ListEnrichmentResultsByCase(context.Context, *ListEnrichmentResultsByCaseRequest) (*ListEnrichmentResultsByCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrichmentResultsByCase not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) ListEnrichmentResultsByObservable(context.Context, *ListEnrichmentResultsByObservableRequest) (*ListEnrichmentResultsByObservableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrichmentResultsByObservable not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) ListThreatLookupResultsByCase(context.Context, *ListThreatLookupResultsByCaseRequest) (*ListThreatLookupResultsByCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListThreatLookupResultsByCase not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) ListThreatLookupResultsByObservable(context.Context, *ListThreatLookupResultsByObservableRequest) (*ListThreatLookupResultsByObservableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListThreatLookupResultsByObservable not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) GetThreatLookupSummaryByObservable(context.Context, *GetThreatLookupSummaryByObservableRequest) (*GetThreatLookupSummaryByObservableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThreatLookupSummaryByObservable not implemented")
}
func (UnimplementedEnrichmentThreatServiceServer) mustEmbedUnimplementedEnrichmentThreatServiceServer() {
}
func (UnimplementedEnrichmentThreatServiceServer) testEmbeddedByValue() {}

// UnsafeEnrichmentThreatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrichmentThreatServiceServer will
// result in compilation errors.
type UnsafeEnrichmentThreatServiceServer interface {
	mustEmbedUnimplementedEnrichmentThreatServiceServer()
}

func RegisterEnrichmentThreatServiceServer(s grpc.ServiceRegistrar, srv EnrichmentThreatServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnrichmentThreatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrichmentThreatService_ServiceDesc, srv)
}

func _EnrichmentThreatService_UpsertEnrichmentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEnrichmentResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).UpsertEnrichmentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_UpsertEnrichmentResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).UpsertEnrichmentResult(ctx, req.(*UpsertEnrichmentResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentThreatService_UpsertThreatLookupResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertThreatLookupResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).UpsertThreatLookupResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_UpsertThreatLookupResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).UpsertThreatLookupResult(ctx, req.(*UpsertThreatLookupResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentThreatService_ListEnrichmentResultsByCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrichmentResultsByCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).ListEnrichmentResultsByCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_ListEnrichmentResultsByCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).ListEnrichmentResultsByCase(ctx, req.(*ListEnrichmentResultsByCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentThreatService_ListEnrichmentResultsByObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrichmentResultsByObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).ListEnrichmentResultsByObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_ListEnrichmentResultsByObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).ListEnrichmentResultsByObservable(ctx, req.(*ListEnrichmentResultsByObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentThreatService_ListThreatLookupResultsByCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThreatLookupResultsByCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).ListThreatLookupResultsByCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_ListThreatLookupResultsByCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).ListThreatLookupResultsByCase(ctx, req.(*ListThreatLookupResultsByCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentThreatService_ListThreatLookupResultsByObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThreatLookupResultsByObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).ListThreatLookupResultsByObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_ListThreatLookupResultsByObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).ListThreatLookupResultsByObservable(ctx, req.(*ListThreatLookupResultsByObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentThreatService_GetThreatLookupSummaryByObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreatLookupSummaryByObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentThreatServiceServer).GetThreatLookupSummaryByObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentThreatService_GetThreatLookupSummaryByObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentThreatServiceServer).GetThreatLookupSummaryByObservable(ctx, req.(*GetThreatLookupSummaryByObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrichmentThreatService_ServiceDesc is the grpc.ServiceDesc for EnrichmentThreatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrichmentThreatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enrichment_threat_service.EnrichmentThreatService",
	HandlerType: (*EnrichmentThreatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertEnrichmentResult",
			Handler:    _EnrichmentThreatService_UpsertEnrichmentResult_Handler,
		},
		{
			MethodName: "UpsertThreatLookupResult",
			Handler:    _EnrichmentThreatService_UpsertThreatLookupResult_Handler,
		},
		{
			MethodName: "ListEnrichmentResultsByCase",
			Handler:    _EnrichmentThreatService_ListEnrichmentResultsByCase_Handler,
		},
		{
			MethodName: "ListEnrichmentResultsByObservable",
			Handler:    _EnrichmentThreatService_ListEnrichmentResultsByObservable_Handler,
		},
		{
			MethodName: "ListThreatLookupResultsByCase",
			Handler:    _EnrichmentThreatService_ListThreatLookupResultsByCase_Handler,
		},
		{
			MethodName: "ListThreatLookupResultsByObservable",
			Handler:    _EnrichmentThreatService_ListThreatLookupResultsByObservable_Handler,
		},
		{
			MethodName: "GetThreatLookupSummaryByObservable",
			Handler:    _EnrichmentThreatService_GetThreatLookupSummaryByObservable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enrichment_threat_service.proto",
}
