-- Add incident form fields to cases table (create-incident UI).

ALTER TABLE cases ADD COLUMN IF NOT EXISTS followup_time TIMESTAMPTZ;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS subcategory VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS source VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS source_tool VARCHAR(255);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS source_tool_feature VARCHAR(255);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS configuration_item VARCHAR(255);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS soc_notes TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS next_steps TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS csirt_classification VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS soc_lead_user_id UUID;
