// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: proto/case_service.proto

package case_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCaseRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShortDescription    string                 `protobuf:"bytes,1,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	State               string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Priority            string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Severity            string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	OpenedByUserId      string                 `protobuf:"bytes,6,opt,name=opened_by_user_id,json=openedByUserId,proto3" json:"opened_by_user_id,omitempty"`
	OpenedTime          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=opened_time,json=openedTime,proto3" json:"opened_time,omitempty"`
	EventOccurredTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=event_occurred_time,json=eventOccurredTime,proto3" json:"event_occurred_time,omitempty"`
	EventReceivedTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=event_received_time,json=eventReceivedTime,proto3" json:"event_received_time,omitempty"`
	AffectedUserId      string                 `protobuf:"bytes,10,opt,name=affected_user_id,json=affectedUserId,proto3" json:"affected_user_id,omitempty"`
	AssignedUserId      string                 `protobuf:"bytes,11,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	AssignmentGroupId   string                 `protobuf:"bytes,12,opt,name=assignment_group_id,json=assignmentGroupId,proto3" json:"assignment_group_id,omitempty"`
	AlertRuleId         string                 `protobuf:"bytes,13,opt,name=alert_rule_id,json=alertRuleId,proto3" json:"alert_rule_id,omitempty"`
	Accuracy            string                 `protobuf:"bytes,14,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Determination       string                 `protobuf:"bytes,15,opt,name=determination,proto3" json:"determination,omitempty"`
	Impact              string                 `protobuf:"bytes,16,opt,name=impact,proto3" json:"impact,omitempty"`
	FollowupTime        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=followup_time,json=followupTime,proto3" json:"followup_time,omitempty"`
	Category            string                 `protobuf:"bytes,18,opt,name=category,proto3" json:"category,omitempty"`
	Subcategory         string                 `protobuf:"bytes,19,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	Source              string                 `protobuf:"bytes,20,opt,name=source,proto3" json:"source,omitempty"`
	SourceTool          string                 `protobuf:"bytes,21,opt,name=source_tool,json=sourceTool,proto3" json:"source_tool,omitempty"`
	SourceToolFeature   string                 `protobuf:"bytes,22,opt,name=source_tool_feature,json=sourceToolFeature,proto3" json:"source_tool_feature,omitempty"`
	ConfigurationItem   string                 `protobuf:"bytes,23,opt,name=configuration_item,json=configurationItem,proto3" json:"configuration_item,omitempty"`
	SocNotes            string                 `protobuf:"bytes,24,opt,name=soc_notes,json=socNotes,proto3" json:"soc_notes,omitempty"`
	NextSteps           string                 `protobuf:"bytes,25,opt,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	CsirtClassification string                 `protobuf:"bytes,26,opt,name=csirt_classification,json=csirtClassification,proto3" json:"csirt_classification,omitempty"`
	SocLeadUserId       string                 `protobuf:"bytes,27,opt,name=soc_lead_user_id,json=socLeadUserId,proto3" json:"soc_lead_user_id,omitempty"`
	NotificationTime    *timestamppb.Timestamp `protobuf:"bytes,28,opt,name=notification_time,json=notificationTime,proto3" json:"notification_time,omitempty"`
	IsAffectedUserVip   bool                   `protobuf:"varint,29,opt,name=is_affected_user_vip,json=isAffectedUserVip,proto3" json:"is_affected_user_vip,omitempty"`
	RequestedByUserId   string                 `protobuf:"bytes,30,opt,name=requested_by_user_id,json=requestedByUserId,proto3" json:"requested_by_user_id,omitempty"`
	EnvironmentLevel    string                 `protobuf:"bytes,31,opt,name=environment_level,json=environmentLevel,proto3" json:"environment_level,omitempty"`
	EnvironmentType     string                 `protobuf:"bytes,32,opt,name=environment_type,json=environmentType,proto3" json:"environment_type,omitempty"`
	Pdn                 string                 `protobuf:"bytes,33,opt,name=pdn,proto3" json:"pdn,omitempty"`
	ImpactedObject      string                 `protobuf:"bytes,34,opt,name=impacted_object,json=impactedObject,proto3" json:"impacted_object,omitempty"`
	Mttr                string                 `protobuf:"bytes,35,opt,name=mttr,proto3" json:"mttr,omitempty"`
	EngineeringDocument string                 `protobuf:"bytes,36,opt,name=engineering_document,json=engineeringDocument,proto3" json:"engineering_document,omitempty"`
	ResponseDocument    string                 `protobuf:"bytes,37,opt,name=response_document,json=responseDocument,proto3" json:"response_document,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateCaseRequest) Reset() {
	*x = CreateCaseRequest{}
	mi := &file_proto_case_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaseRequest) ProtoMessage() {}

func (x *CreateCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaseRequest.ProtoReflect.Descriptor instead.
func (*CreateCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCaseRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateCaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCaseRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateCaseRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateCaseRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CreateCaseRequest) GetOpenedByUserId() string {
	if x != nil {
		return x.OpenedByUserId
	}
	return ""
}

func (x *CreateCaseRequest) GetOpenedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedTime
	}
	return nil
}

func (x *CreateCaseRequest) GetEventOccurredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventOccurredTime
	}
	return nil
}

func (x *CreateCaseRequest) GetEventReceivedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventReceivedTime
	}
	return nil
}

func (x *CreateCaseRequest) GetAffectedUserId() string {
	if x != nil {
		return x.AffectedUserId
	}
	return ""
}

func (x *CreateCaseRequest) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

func (x *CreateCaseRequest) GetAssignmentGroupId() string {
	if x != nil {
		return x.AssignmentGroupId
	}
	return ""
}

func (x *CreateCaseRequest) GetAlertRuleId() string {
	if x != nil {
		return x.AlertRuleId
	}
	return ""
}

func (x *CreateCaseRequest) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *CreateCaseRequest) GetDetermination() string {
	if x != nil {
		return x.Determination
	}
	return ""
}

func (x *CreateCaseRequest) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *CreateCaseRequest) GetFollowupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowupTime
	}
	return nil
}

func (x *CreateCaseRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateCaseRequest) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

func (x *CreateCaseRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateCaseRequest) GetSourceTool() string {
	if x != nil {
		return x.SourceTool
	}
	return ""
}

func (x *CreateCaseRequest) GetSourceToolFeature() string {
	if x != nil {
		return x.SourceToolFeature
	}
	return ""
}

func (x *CreateCaseRequest) GetConfigurationItem() string {
	if x != nil {
		return x.ConfigurationItem
	}
	return ""
}

func (x *CreateCaseRequest) GetSocNotes() string {
	if x != nil {
		return x.SocNotes
	}
	return ""
}

func (x *CreateCaseRequest) GetNextSteps() string {
	if x != nil {
		return x.NextSteps
	}
	return ""
}

func (x *CreateCaseRequest) GetCsirtClassification() string {
	if x != nil {
		return x.CsirtClassification
	}
	return ""
}

func (x *CreateCaseRequest) GetSocLeadUserId() string {
	if x != nil {
		return x.SocLeadUserId
	}
	return ""
}

func (x *CreateCaseRequest) GetNotificationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotificationTime
	}
	return nil
}

func (x *CreateCaseRequest) GetIsAffectedUserVip() bool {
	if x != nil {
		return x.IsAffectedUserVip
	}
	return false
}

func (x *CreateCaseRequest) GetRequestedByUserId() string {
	if x != nil {
		return x.RequestedByUserId
	}
	return ""
}

func (x *CreateCaseRequest) GetEnvironmentLevel() string {
	if x != nil {
		return x.EnvironmentLevel
	}
	return ""
}

func (x *CreateCaseRequest) GetEnvironmentType() string {
	if x != nil {
		return x.EnvironmentType
	}
	return ""
}

func (x *CreateCaseRequest) GetPdn() string {
	if x != nil {
		return x.Pdn
	}
	return ""
}

func (x *CreateCaseRequest) GetImpactedObject() string {
	if x != nil {
		return x.ImpactedObject
	}
	return ""
}

func (x *CreateCaseRequest) GetMttr() string {
	if x != nil {
		return x.Mttr
	}
	return ""
}

func (x *CreateCaseRequest) GetEngineeringDocument() string {
	if x != nil {
		return x.EngineeringDocument
	}
	return ""
}

func (x *CreateCaseRequest) GetResponseDocument() string {
	if x != nil {
		return x.ResponseDocument
	}
	return ""
}

type CreateCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CaseNumber    string                 `protobuf:"bytes,2,opt,name=case_number,json=caseNumber,proto3" json:"case_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCaseResponse) Reset() {
	*x = CreateCaseResponse{}
	mi := &file_proto_case_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaseResponse) ProtoMessage() {}

func (x *CreateCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaseResponse.ProtoReflect.Descriptor instead.
func (*CreateCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCaseResponse) GetCaseNumber() string {
	if x != nil {
		return x.CaseNumber
	}
	return ""
}

type UpdateCaseRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortDescription    *string                `protobuf:"bytes,2,opt,name=short_description,json=shortDescription,proto3,oneof" json:"short_description,omitempty"`
	Description         *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	State               *string                `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Priority            *string                `protobuf:"bytes,5,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Severity            *string                `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	AffectedUserId      *string                `protobuf:"bytes,7,opt,name=affected_user_id,json=affectedUserId,proto3,oneof" json:"affected_user_id,omitempty"`
	AssignedUserId      *string                `protobuf:"bytes,8,opt,name=assigned_user_id,json=assignedUserId,proto3,oneof" json:"assigned_user_id,omitempty"`
	AssignmentGroupId   *string                `protobuf:"bytes,9,opt,name=assignment_group_id,json=assignmentGroupId,proto3,oneof" json:"assignment_group_id,omitempty"`
	Accuracy            *string                `protobuf:"bytes,10,opt,name=accuracy,proto3,oneof" json:"accuracy,omitempty"`
	Determination       *string                `protobuf:"bytes,11,opt,name=determination,proto3,oneof" json:"determination,omitempty"`
	Impact              *string                `protobuf:"bytes,12,opt,name=impact,proto3,oneof" json:"impact,omitempty"`
	VersionNo           int32                  `protobuf:"varint,13,opt,name=version_no,json=versionNo,proto3" json:"version_no,omitempty"`
	FollowupTime        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=followup_time,json=followupTime,proto3,oneof" json:"followup_time,omitempty"`
	Category            *string                `protobuf:"bytes,15,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Subcategory         *string                `protobuf:"bytes,16,opt,name=subcategory,proto3,oneof" json:"subcategory,omitempty"`
	Source              *string                `protobuf:"bytes,17,opt,name=source,proto3,oneof" json:"source,omitempty"`
	SourceTool          *string                `protobuf:"bytes,18,opt,name=source_tool,json=sourceTool,proto3,oneof" json:"source_tool,omitempty"`
	SourceToolFeature   *string                `protobuf:"bytes,19,opt,name=source_tool_feature,json=sourceToolFeature,proto3,oneof" json:"source_tool_feature,omitempty"`
	ConfigurationItem   *string                `protobuf:"bytes,20,opt,name=configuration_item,json=configurationItem,proto3,oneof" json:"configuration_item,omitempty"`
	SocNotes            *string                `protobuf:"bytes,21,opt,name=soc_notes,json=socNotes,proto3,oneof" json:"soc_notes,omitempty"`
	NextSteps           *string                `protobuf:"bytes,22,opt,name=next_steps,json=nextSteps,proto3,oneof" json:"next_steps,omitempty"`
	CsirtClassification *string                `protobuf:"bytes,23,opt,name=csirt_classification,json=csirtClassification,proto3,oneof" json:"csirt_classification,omitempty"`
	SocLeadUserId       *string                `protobuf:"bytes,24,opt,name=soc_lead_user_id,json=socLeadUserId,proto3,oneof" json:"soc_lead_user_id,omitempty"`
	NotificationTime    *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=notification_time,json=notificationTime,proto3,oneof" json:"notification_time,omitempty"`
	IsAffectedUserVip   *bool                  `protobuf:"varint,26,opt,name=is_affected_user_vip,json=isAffectedUserVip,proto3,oneof" json:"is_affected_user_vip,omitempty"`
	RequestedByUserId   *string                `protobuf:"bytes,27,opt,name=requested_by_user_id,json=requestedByUserId,proto3,oneof" json:"requested_by_user_id,omitempty"`
	EnvironmentLevel    *string                `protobuf:"bytes,28,opt,name=environment_level,json=environmentLevel,proto3,oneof" json:"environment_level,omitempty"`
	EnvironmentType     *string                `protobuf:"bytes,29,opt,name=environment_type,json=environmentType,proto3,oneof" json:"environment_type,omitempty"`
	Pdn                 *string                `protobuf:"bytes,30,opt,name=pdn,proto3,oneof" json:"pdn,omitempty"`
	ImpactedObject      *string                `protobuf:"bytes,31,opt,name=impacted_object,json=impactedObject,proto3,oneof" json:"impacted_object,omitempty"`
	Mttr                *string                `protobuf:"bytes,32,opt,name=mttr,proto3,oneof" json:"mttr,omitempty"`
	ReassignmentCount   *int32                 `protobuf:"varint,33,opt,name=reassignment_count,json=reassignmentCount,proto3,oneof" json:"reassignment_count,omitempty"`
	AssignedToCount     *int32                 `protobuf:"varint,34,opt,name=assigned_to_count,json=assignedToCount,proto3,oneof" json:"assigned_to_count,omitempty"`
	EngineeringDocument *string                `protobuf:"bytes,35,opt,name=engineering_document,json=engineeringDocument,proto3,oneof" json:"engineering_document,omitempty"`
	ResponseDocument    *string                `protobuf:"bytes,36,opt,name=response_document,json=responseDocument,proto3,oneof" json:"response_document,omitempty"`
	ClosureReason       *string                `protobuf:"bytes,37,opt,name=closure_reason,json=closureReason,proto3,oneof" json:"closure_reason,omitempty"`
	EventOccurredTime   *timestamppb.Timestamp `protobuf:"bytes,38,opt,name=event_occurred_time,json=eventOccurredTime,proto3,oneof" json:"event_occurred_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateCaseRequest) Reset() {
	*x = UpdateCaseRequest{}
	mi := &file_proto_case_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaseRequest) ProtoMessage() {}

func (x *UpdateCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCaseRequest) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *UpdateCaseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCaseRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *UpdateCaseRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *UpdateCaseRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *UpdateCaseRequest) GetAffectedUserId() string {
	if x != nil && x.AffectedUserId != nil {
		return *x.AffectedUserId
	}
	return ""
}

func (x *UpdateCaseRequest) GetAssignedUserId() string {
	if x != nil && x.AssignedUserId != nil {
		return *x.AssignedUserId
	}
	return ""
}

func (x *UpdateCaseRequest) GetAssignmentGroupId() string {
	if x != nil && x.AssignmentGroupId != nil {
		return *x.AssignmentGroupId
	}
	return ""
}

func (x *UpdateCaseRequest) GetAccuracy() string {
	if x != nil && x.Accuracy != nil {
		return *x.Accuracy
	}
	return ""
}

func (x *UpdateCaseRequest) GetDetermination() string {
	if x != nil && x.Determination != nil {
		return *x.Determination
	}
	return ""
}

func (x *UpdateCaseRequest) GetImpact() string {
	if x != nil && x.Impact != nil {
		return *x.Impact
	}
	return ""
}

func (x *UpdateCaseRequest) GetVersionNo() int32 {
	if x != nil {
		return x.VersionNo
	}
	return 0
}

func (x *UpdateCaseRequest) GetFollowupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowupTime
	}
	return nil
}

func (x *UpdateCaseRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateCaseRequest) GetSubcategory() string {
	if x != nil && x.Subcategory != nil {
		return *x.Subcategory
	}
	return ""
}

func (x *UpdateCaseRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *UpdateCaseRequest) GetSourceTool() string {
	if x != nil && x.SourceTool != nil {
		return *x.SourceTool
	}
	return ""
}

func (x *UpdateCaseRequest) GetSourceToolFeature() string {
	if x != nil && x.SourceToolFeature != nil {
		return *x.SourceToolFeature
	}
	return ""
}

func (x *UpdateCaseRequest) GetConfigurationItem() string {
	if x != nil && x.ConfigurationItem != nil {
		return *x.ConfigurationItem
	}
	return ""
}

func (x *UpdateCaseRequest) GetSocNotes() string {
	if x != nil && x.SocNotes != nil {
		return *x.SocNotes
	}
	return ""
}

func (x *UpdateCaseRequest) GetNextSteps() string {
	if x != nil && x.NextSteps != nil {
		return *x.NextSteps
	}
	return ""
}

func (x *UpdateCaseRequest) GetCsirtClassification() string {
	if x != nil && x.CsirtClassification != nil {
		return *x.CsirtClassification
	}
	return ""
}

func (x *UpdateCaseRequest) GetSocLeadUserId() string {
	if x != nil && x.SocLeadUserId != nil {
		return *x.SocLeadUserId
	}
	return ""
}

func (x *UpdateCaseRequest) GetNotificationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotificationTime
	}
	return nil
}

func (x *UpdateCaseRequest) GetIsAffectedUserVip() bool {
	if x != nil && x.IsAffectedUserVip != nil {
		return *x.IsAffectedUserVip
	}
	return false
}

func (x *UpdateCaseRequest) GetRequestedByUserId() string {
	if x != nil && x.RequestedByUserId != nil {
		return *x.RequestedByUserId
	}
	return ""
}

func (x *UpdateCaseRequest) GetEnvironmentLevel() string {
	if x != nil && x.EnvironmentLevel != nil {
		return *x.EnvironmentLevel
	}
	return ""
}

func (x *UpdateCaseRequest) GetEnvironmentType() string {
	if x != nil && x.EnvironmentType != nil {
		return *x.EnvironmentType
	}
	return ""
}

func (x *UpdateCaseRequest) GetPdn() string {
	if x != nil && x.Pdn != nil {
		return *x.Pdn
	}
	return ""
}

func (x *UpdateCaseRequest) GetImpactedObject() string {
	if x != nil && x.ImpactedObject != nil {
		return *x.ImpactedObject
	}
	return ""
}

func (x *UpdateCaseRequest) GetMttr() string {
	if x != nil && x.Mttr != nil {
		return *x.Mttr
	}
	return ""
}

func (x *UpdateCaseRequest) GetReassignmentCount() int32 {
	if x != nil && x.ReassignmentCount != nil {
		return *x.ReassignmentCount
	}
	return 0
}

func (x *UpdateCaseRequest) GetAssignedToCount() int32 {
	if x != nil && x.AssignedToCount != nil {
		return *x.AssignedToCount
	}
	return 0
}

func (x *UpdateCaseRequest) GetEngineeringDocument() string {
	if x != nil && x.EngineeringDocument != nil {
		return *x.EngineeringDocument
	}
	return ""
}

func (x *UpdateCaseRequest) GetResponseDocument() string {
	if x != nil && x.ResponseDocument != nil {
		return *x.ResponseDocument
	}
	return ""
}

func (x *UpdateCaseRequest) GetClosureReason() string {
	if x != nil && x.ClosureReason != nil {
		return *x.ClosureReason
	}
	return ""
}

func (x *UpdateCaseRequest) GetEventOccurredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventOccurredTime
	}
	return nil
}

type UpdateCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Case          *Case                  `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCaseResponse) Reset() {
	*x = UpdateCaseResponse{}
	mi := &file_proto_case_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaseResponse) ProtoMessage() {}

func (x *UpdateCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCaseResponse) GetCase() *Case {
	if x != nil {
		return x.Case
	}
	return nil
}

type AssignCaseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CaseId            string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	AssignedUserId    string                 `protobuf:"bytes,2,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	AssignmentGroupId string                 `protobuf:"bytes,3,opt,name=assignment_group_id,json=assignmentGroupId,proto3" json:"assignment_group_id,omitempty"`
	VersionNo         int32                  `protobuf:"varint,4,opt,name=version_no,json=versionNo,proto3" json:"version_no,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AssignCaseRequest) Reset() {
	*x = AssignCaseRequest{}
	mi := &file_proto_case_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCaseRequest) ProtoMessage() {}

func (x *AssignCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCaseRequest.ProtoReflect.Descriptor instead.
func (*AssignCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{4}
}

func (x *AssignCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *AssignCaseRequest) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

func (x *AssignCaseRequest) GetAssignmentGroupId() string {
	if x != nil {
		return x.AssignmentGroupId
	}
	return ""
}

func (x *AssignCaseRequest) GetVersionNo() int32 {
	if x != nil {
		return x.VersionNo
	}
	return 0
}

type AssignCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Case          *Case                  `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCaseResponse) Reset() {
	*x = AssignCaseResponse{}
	mi := &file_proto_case_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCaseResponse) ProtoMessage() {}

func (x *AssignCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCaseResponse.ProtoReflect.Descriptor instead.
func (*AssignCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{5}
}

func (x *AssignCaseResponse) GetCase() *Case {
	if x != nil {
		return x.Case
	}
	return nil
}

type CloseCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	ClosureCode   string                 `protobuf:"bytes,2,opt,name=closure_code,json=closureCode,proto3" json:"closure_code,omitempty"`
	ClosureReason string                 `protobuf:"bytes,3,opt,name=closure_reason,json=closureReason,proto3" json:"closure_reason,omitempty"`
	VersionNo     int32                  `protobuf:"varint,4,opt,name=version_no,json=versionNo,proto3" json:"version_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCaseRequest) Reset() {
	*x = CloseCaseRequest{}
	mi := &file_proto_case_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCaseRequest) ProtoMessage() {}

func (x *CloseCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCaseRequest.ProtoReflect.Descriptor instead.
func (*CloseCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{6}
}

func (x *CloseCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CloseCaseRequest) GetClosureCode() string {
	if x != nil {
		return x.ClosureCode
	}
	return ""
}

func (x *CloseCaseRequest) GetClosureReason() string {
	if x != nil {
		return x.ClosureReason
	}
	return ""
}

func (x *CloseCaseRequest) GetVersionNo() int32 {
	if x != nil {
		return x.VersionNo
	}
	return 0
}

type CloseCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Case          *Case                  `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCaseResponse) Reset() {
	*x = CloseCaseResponse{}
	mi := &file_proto_case_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCaseResponse) ProtoMessage() {}

func (x *CloseCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCaseResponse.ProtoReflect.Descriptor instead.
func (*CloseCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{7}
}

func (x *CloseCaseResponse) GetCase() *Case {
	if x != nil {
		return x.Case
	}
	return nil
}

type AddWorknoteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CaseId          string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	NoteText        string                 `protobuf:"bytes,2,opt,name=note_text,json=noteText,proto3" json:"note_text,omitempty"`
	NoteType        string                 `protobuf:"bytes,3,opt,name=note_type,json=noteType,proto3" json:"note_type,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,4,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddWorknoteRequest) Reset() {
	*x = AddWorknoteRequest{}
	mi := &file_proto_case_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorknoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorknoteRequest) ProtoMessage() {}

func (x *AddWorknoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorknoteRequest.ProtoReflect.Descriptor instead.
func (*AddWorknoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddWorknoteRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *AddWorknoteRequest) GetNoteText() string {
	if x != nil {
		return x.NoteText
	}
	return ""
}

func (x *AddWorknoteRequest) GetNoteType() string {
	if x != nil {
		return x.NoteType
	}
	return ""
}

func (x *AddWorknoteRequest) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

type AddWorknoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worknote      *Worknote              `protobuf:"bytes,1,opt,name=worknote,proto3" json:"worknote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorknoteResponse) Reset() {
	*x = AddWorknoteResponse{}
	mi := &file_proto_case_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorknoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorknoteResponse) ProtoMessage() {}

func (x *AddWorknoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorknoteResponse.ProtoReflect.Descriptor instead.
func (*AddWorknoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{9}
}

func (x *AddWorknoteResponse) GetWorknote() *Worknote {
	if x != nil {
		return x.Worknote
	}
	return nil
}

type GetCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseRequest) Reset() {
	*x = GetCaseRequest{}
	mi := &file_proto_case_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseRequest) ProtoMessage() {}

func (x *GetCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseRequest.ProtoReflect.Descriptor instead.
func (*GetCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type GetCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Case          *Case                  `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseResponse) Reset() {
	*x = GetCaseResponse{}
	mi := &file_proto_case_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseResponse) ProtoMessage() {}

func (x *GetCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseResponse.ProtoReflect.Descriptor instead.
func (*GetCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCaseResponse) GetCase() *Case {
	if x != nil {
		return x.Case
	}
	return nil
}

type ListCasesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PageSize          int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	State             *string                `protobuf:"bytes,3,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Priority          *string                `protobuf:"bytes,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Severity          *string                `protobuf:"bytes,5,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	AssignmentGroupId *string                `protobuf:"bytes,6,opt,name=assignment_group_id,json=assignmentGroupId,proto3,oneof" json:"assignment_group_id,omitempty"`
	AssignedUserId    *string                `protobuf:"bytes,7,opt,name=assigned_user_id,json=assignedUserId,proto3,oneof" json:"assigned_user_id,omitempty"`
	AffectedUserId    *string                `protobuf:"bytes,8,opt,name=affected_user_id,json=affectedUserId,proto3,oneof" json:"affected_user_id,omitempty"`
	OpenedTimeAfter   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=opened_time_after,json=openedTimeAfter,proto3,oneof" json:"opened_time_after,omitempty"`
	OpenedTimeBefore  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=opened_time_before,json=openedTimeBefore,proto3,oneof" json:"opened_time_before,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListCasesRequest) Reset() {
	*x = ListCasesRequest{}
	mi := &file_proto_case_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCasesRequest) ProtoMessage() {}

func (x *ListCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCasesRequest.ProtoReflect.Descriptor instead.
func (*ListCasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListCasesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCasesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCasesRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *ListCasesRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *ListCasesRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ListCasesRequest) GetAssignmentGroupId() string {
	if x != nil && x.AssignmentGroupId != nil {
		return *x.AssignmentGroupId
	}
	return ""
}

func (x *ListCasesRequest) GetAssignedUserId() string {
	if x != nil && x.AssignedUserId != nil {
		return *x.AssignedUserId
	}
	return ""
}

func (x *ListCasesRequest) GetAffectedUserId() string {
	if x != nil && x.AffectedUserId != nil {
		return *x.AffectedUserId
	}
	return ""
}

func (x *ListCasesRequest) GetOpenedTimeAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedTimeAfter
	}
	return nil
}

func (x *ListCasesRequest) GetOpenedTimeBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedTimeBefore
	}
	return nil
}

type ListCasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Case                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCasesResponse) Reset() {
	*x = ListCasesResponse{}
	mi := &file_proto_case_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCasesResponse) ProtoMessage() {}

func (x *ListCasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCasesResponse.ProtoReflect.Descriptor instead.
func (*ListCasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListCasesResponse) GetItems() []*Case {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCasesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListWorknotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorknotesRequest) Reset() {
	*x = ListWorknotesRequest{}
	mi := &file_proto_case_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorknotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorknotesRequest) ProtoMessage() {}

func (x *ListWorknotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorknotesRequest.ProtoReflect.Descriptor instead.
func (*ListWorknotesRequest) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListWorknotesRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ListWorknotesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorknotesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorknotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Worknote            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorknotesResponse) Reset() {
	*x = ListWorknotesResponse{}
	mi := &file_proto_case_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorknotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorknotesResponse) ProtoMessage() {}

func (x *ListWorknotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorknotesResponse.ProtoReflect.Descriptor instead.
func (*ListWorknotesResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListWorknotesResponse) GetItems() []*Worknote {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListWorknotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Case struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CaseNumber            string                 `protobuf:"bytes,2,opt,name=case_number,json=caseNumber,proto3" json:"case_number,omitempty"`
	ShortDescription      string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Description           string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	State                 string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Priority              string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Severity              string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	OpenedByUserId        string                 `protobuf:"bytes,8,opt,name=opened_by_user_id,json=openedByUserId,proto3" json:"opened_by_user_id,omitempty"`
	OpenedTime            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=opened_time,json=openedTime,proto3" json:"opened_time,omitempty"`
	EventOccurredTime     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=event_occurred_time,json=eventOccurredTime,proto3" json:"event_occurred_time,omitempty"`
	EventReceivedTime     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=event_received_time,json=eventReceivedTime,proto3" json:"event_received_time,omitempty"`
	AffectedUserId        string                 `protobuf:"bytes,12,opt,name=affected_user_id,json=affectedUserId,proto3" json:"affected_user_id,omitempty"`
	AssignedUserId        string                 `protobuf:"bytes,13,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	AssignmentGroupId     string                 `protobuf:"bytes,14,opt,name=assignment_group_id,json=assignmentGroupId,proto3" json:"assignment_group_id,omitempty"`
	AlertRuleId           string                 `protobuf:"bytes,15,opt,name=alert_rule_id,json=alertRuleId,proto3" json:"alert_rule_id,omitempty"`
	ActiveDurationSeconds int64                  `protobuf:"varint,16,opt,name=active_duration_seconds,json=activeDurationSeconds,proto3" json:"active_duration_seconds,omitempty"`
	Accuracy              string                 `protobuf:"bytes,17,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Determination         string                 `protobuf:"bytes,18,opt,name=determination,proto3" json:"determination,omitempty"`
	Impact                string                 `protobuf:"bytes,19,opt,name=impact,proto3" json:"impact,omitempty"`
	ClosureCode           string                 `protobuf:"bytes,20,opt,name=closure_code,json=closureCode,proto3" json:"closure_code,omitempty"`
	ClosureReason         string                 `protobuf:"bytes,21,opt,name=closure_reason,json=closureReason,proto3" json:"closure_reason,omitempty"`
	ClosedByUserId        string                 `protobuf:"bytes,22,opt,name=closed_by_user_id,json=closedByUserId,proto3" json:"closed_by_user_id,omitempty"`
	ClosedTime            *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=closed_time,json=closedTime,proto3" json:"closed_time,omitempty"`
	IsActive              bool                   `protobuf:"varint,24,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	VersionNo             int32                  `protobuf:"varint,25,opt,name=version_no,json=versionNo,proto3" json:"version_no,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FollowupTime          *timestamppb.Timestamp `protobuf:"bytes,28,opt,name=followup_time,json=followupTime,proto3" json:"followup_time,omitempty"`
	Category              string                 `protobuf:"bytes,29,opt,name=category,proto3" json:"category,omitempty"`
	Subcategory           string                 `protobuf:"bytes,30,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	Source                string                 `protobuf:"bytes,31,opt,name=source,proto3" json:"source,omitempty"`
	SourceTool            string                 `protobuf:"bytes,32,opt,name=source_tool,json=sourceTool,proto3" json:"source_tool,omitempty"`
	SourceToolFeature     string                 `protobuf:"bytes,33,opt,name=source_tool_feature,json=sourceToolFeature,proto3" json:"source_tool_feature,omitempty"`
	ConfigurationItem     string                 `protobuf:"bytes,34,opt,name=configuration_item,json=configurationItem,proto3" json:"configuration_item,omitempty"`
	SocNotes              string                 `protobuf:"bytes,35,opt,name=soc_notes,json=socNotes,proto3" json:"soc_notes,omitempty"`
	NextSteps             string                 `protobuf:"bytes,36,opt,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	CsirtClassification   string                 `protobuf:"bytes,37,opt,name=csirt_classification,json=csirtClassification,proto3" json:"csirt_classification,omitempty"`
	SocLeadUserId         string                 `protobuf:"bytes,38,opt,name=soc_lead_user_id,json=socLeadUserId,proto3" json:"soc_lead_user_id,omitempty"`
	RequestedByUserId     string                 `protobuf:"bytes,39,opt,name=requested_by_user_id,json=requestedByUserId,proto3" json:"requested_by_user_id,omitempty"`
	EnvironmentLevel      string                 `protobuf:"bytes,40,opt,name=environment_level,json=environmentLevel,proto3" json:"environment_level,omitempty"`
	EnvironmentType       string                 `protobuf:"bytes,41,opt,name=environment_type,json=environmentType,proto3" json:"environment_type,omitempty"`
	Pdn                   string                 `protobuf:"bytes,42,opt,name=pdn,proto3" json:"pdn,omitempty"`
	ImpactedObject        string                 `protobuf:"bytes,43,opt,name=impacted_object,json=impactedObject,proto3" json:"impacted_object,omitempty"`
	NotificationTime      *timestamppb.Timestamp `protobuf:"bytes,44,opt,name=notification_time,json=notificationTime,proto3" json:"notification_time,omitempty"`
	Mttr                  string                 `protobuf:"bytes,45,opt,name=mttr,proto3" json:"mttr,omitempty"`
	ReassignmentCount     int32                  `protobuf:"varint,46,opt,name=reassignment_count,json=reassignmentCount,proto3" json:"reassignment_count,omitempty"`
	AssignedToCount       int32                  `protobuf:"varint,47,opt,name=assigned_to_count,json=assignedToCount,proto3" json:"assigned_to_count,omitempty"`
	IsAffectedUserVip     bool                   `protobuf:"varint,48,opt,name=is_affected_user_vip,json=isAffectedUserVip,proto3" json:"is_affected_user_vip,omitempty"`
	EngineeringDocument   string                 `protobuf:"bytes,49,opt,name=engineering_document,json=engineeringDocument,proto3" json:"engineering_document,omitempty"`
	ResponseDocument      string                 `protobuf:"bytes,50,opt,name=response_document,json=responseDocument,proto3" json:"response_document,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_proto_case_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{16}
}

func (x *Case) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Case) GetCaseNumber() string {
	if x != nil {
		return x.CaseNumber
	}
	return ""
}

func (x *Case) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Case) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Case) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Case) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Case) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Case) GetOpenedByUserId() string {
	if x != nil {
		return x.OpenedByUserId
	}
	return ""
}

func (x *Case) GetOpenedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedTime
	}
	return nil
}

func (x *Case) GetEventOccurredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventOccurredTime
	}
	return nil
}

func (x *Case) GetEventReceivedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventReceivedTime
	}
	return nil
}

func (x *Case) GetAffectedUserId() string {
	if x != nil {
		return x.AffectedUserId
	}
	return ""
}

func (x *Case) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

func (x *Case) GetAssignmentGroupId() string {
	if x != nil {
		return x.AssignmentGroupId
	}
	return ""
}

func (x *Case) GetAlertRuleId() string {
	if x != nil {
		return x.AlertRuleId
	}
	return ""
}

func (x *Case) GetActiveDurationSeconds() int64 {
	if x != nil {
		return x.ActiveDurationSeconds
	}
	return 0
}

func (x *Case) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *Case) GetDetermination() string {
	if x != nil {
		return x.Determination
	}
	return ""
}

func (x *Case) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *Case) GetClosureCode() string {
	if x != nil {
		return x.ClosureCode
	}
	return ""
}

func (x *Case) GetClosureReason() string {
	if x != nil {
		return x.ClosureReason
	}
	return ""
}

func (x *Case) GetClosedByUserId() string {
	if x != nil {
		return x.ClosedByUserId
	}
	return ""
}

func (x *Case) GetClosedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedTime
	}
	return nil
}

func (x *Case) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Case) GetVersionNo() int32 {
	if x != nil {
		return x.VersionNo
	}
	return 0
}

func (x *Case) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Case) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Case) GetFollowupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowupTime
	}
	return nil
}

func (x *Case) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Case) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

func (x *Case) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Case) GetSourceTool() string {
	if x != nil {
		return x.SourceTool
	}
	return ""
}

func (x *Case) GetSourceToolFeature() string {
	if x != nil {
		return x.SourceToolFeature
	}
	return ""
}

func (x *Case) GetConfigurationItem() string {
	if x != nil {
		return x.ConfigurationItem
	}
	return ""
}

func (x *Case) GetSocNotes() string {
	if x != nil {
		return x.SocNotes
	}
	return ""
}

func (x *Case) GetNextSteps() string {
	if x != nil {
		return x.NextSteps
	}
	return ""
}

func (x *Case) GetCsirtClassification() string {
	if x != nil {
		return x.CsirtClassification
	}
	return ""
}

func (x *Case) GetSocLeadUserId() string {
	if x != nil {
		return x.SocLeadUserId
	}
	return ""
}

func (x *Case) GetRequestedByUserId() string {
	if x != nil {
		return x.RequestedByUserId
	}
	return ""
}

func (x *Case) GetEnvironmentLevel() string {
	if x != nil {
		return x.EnvironmentLevel
	}
	return ""
}

func (x *Case) GetEnvironmentType() string {
	if x != nil {
		return x.EnvironmentType
	}
	return ""
}

func (x *Case) GetPdn() string {
	if x != nil {
		return x.Pdn
	}
	return ""
}

func (x *Case) GetImpactedObject() string {
	if x != nil {
		return x.ImpactedObject
	}
	return ""
}

func (x *Case) GetNotificationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotificationTime
	}
	return nil
}

func (x *Case) GetMttr() string {
	if x != nil {
		return x.Mttr
	}
	return ""
}

func (x *Case) GetReassignmentCount() int32 {
	if x != nil {
		return x.ReassignmentCount
	}
	return 0
}

func (x *Case) GetAssignedToCount() int32 {
	if x != nil {
		return x.AssignedToCount
	}
	return 0
}

func (x *Case) GetIsAffectedUserVip() bool {
	if x != nil {
		return x.IsAffectedUserVip
	}
	return false
}

func (x *Case) GetEngineeringDocument() string {
	if x != nil {
		return x.EngineeringDocument
	}
	return ""
}

func (x *Case) GetResponseDocument() string {
	if x != nil {
		return x.ResponseDocument
	}
	return ""
}

type Worknote struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CaseId          string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	NoteText        string                 `protobuf:"bytes,3,opt,name=note_text,json=noteText,proto3" json:"note_text,omitempty"`
	NoteType        string                 `protobuf:"bytes,4,opt,name=note_type,json=noteType,proto3" json:"note_type,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,5,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted       bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Worknote) Reset() {
	*x = Worknote{}
	mi := &file_proto_case_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worknote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worknote) ProtoMessage() {}

func (x *Worknote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worknote.ProtoReflect.Descriptor instead.
func (*Worknote) Descriptor() ([]byte, []int) {
	return file_proto_case_service_proto_rawDescGZIP(), []int{17}
}

func (x *Worknote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worknote) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *Worknote) GetNoteText() string {
	if x != nil {
		return x.NoteText
	}
	return ""
}

func (x *Worknote) GetNoteType() string {
	if x != nil {
		return x.NoteType
	}
	return ""
}

func (x *Worknote) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

func (x *Worknote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Worknote) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Worknote) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

var File_proto_case_service_proto protoreflect.FileDescriptor

const file_proto_case_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/case_service.proto\x12\fcase_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\f\n" +
	"\x11CreateCaseRequest\x12+\n" +
	"\x11short_description\x18\x01 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12)\n" +
	"\x11opened_by_user_id\x18\x06 \x01(\tR\x0eopenedByUserId\x12;\n" +
	"\vopened_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"openedTime\x12J\n" +
	"\x13event_occurred_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11eventOccurredTime\x12J\n" +
	"\x13event_received_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x11eventReceivedTime\x12(\n" +
	"\x10affected_user_id\x18\n" +
	" \x01(\tR\x0eaffectedUserId\x12(\n" +
	"\x10assigned_user_id\x18\v \x01(\tR\x0eassignedUserId\x12.\n" +
	"\x13assignment_group_id\x18\f \x01(\tR\x11assignmentGroupId\x12\"\n" +
	"\ralert_rule_id\x18\r \x01(\tR\valertRuleId\x12\x1a\n" +
	"\baccuracy\x18\x0e \x01(\tR\baccuracy\x12$\n" +
	"\rdetermination\x18\x0f \x01(\tR\rdetermination\x12\x16\n" +
	"\x06impact\x18\x10 \x01(\tR\x06impact\x12?\n" +
	"\rfollowup_time\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\ffollowupTime\x12\x1a\n" +
	"\bcategory\x18\x12 \x01(\tR\bcategory\x12 \n" +
	"\vsubcategory\x18\x13 \x01(\tR\vsubcategory\x12\x16\n" +
	"\x06source\x18\x14 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_tool\x18\x15 \x01(\tR\n" +
	"sourceTool\x12.\n" +
	"\x13source_tool_feature\x18\x16 \x01(\tR\x11sourceToolFeature\x12-\n" +
	"\x12configuration_item\x18\x17 \x01(\tR\x11configurationItem\x12\x1b\n" +
	"\tsoc_notes\x18\x18 \x01(\tR\bsocNotes\x12\x1d\n" +
	"\n" +
	"next_steps\x18\x19 \x01(\tR\tnextSteps\x121\n" +
	"\x14csirt_classification\x18\x1a \x01(\tR\x13csirtClassification\x12'\n" +
	"\x10soc_lead_user_id\x18\x1b \x01(\tR\rsocLeadUserId\x12G\n" +
	"\x11notification_time\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\x10notificationTime\x12/\n" +
	"\x14is_affected_user_vip\x18\x1d \x01(\bR\x11isAffectedUserVip\x12/\n" +
	"\x14requested_by_user_id\x18\x1e \x01(\tR\x11requestedByUserId\x12+\n" +
	"\x11environment_level\x18\x1f \x01(\tR\x10environmentLevel\x12)\n" +
	"\x10environment_type\x18  \x01(\tR\x0fenvironmentType\x12\x10\n" +
	"\x03pdn\x18! \x01(\tR\x03pdn\x12'\n" +
	"\x0fimpacted_object\x18\" \x01(\tR\x0eimpactedObject\x12\x12\n" +
	"\x04mttr\x18# \x01(\tR\x04mttr\x121\n" +
	"\x14engineering_document\x18$ \x01(\tR\x13engineeringDocument\x12+\n" +
	"\x11response_document\x18% \x01(\tR\x10responseDocument\"E\n" +
	"\x12CreateCaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcase_number\x18\x02 \x01(\tR\n" +
	"caseNumber\"\xb9\x12\n" +
	"\x11UpdateCaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x11short_description\x18\x02 \x01(\tH\x00R\x10shortDescription\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x04 \x01(\tH\x02R\x05state\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x05 \x01(\tH\x03R\bpriority\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x04R\bseverity\x88\x01\x01\x12-\n" +
	"\x10affected_user_id\x18\a \x01(\tH\x05R\x0eaffectedUserId\x88\x01\x01\x12-\n" +
	"\x10assigned_user_id\x18\b \x01(\tH\x06R\x0eassignedUserId\x88\x01\x01\x123\n" +
	"\x13assignment_group_id\x18\t \x01(\tH\aR\x11assignmentGroupId\x88\x01\x01\x12\x1f\n" +
	"\baccuracy\x18\n" +
	" \x01(\tH\bR\baccuracy\x88\x01\x01\x12)\n" +
	"\rdetermination\x18\v \x01(\tH\tR\rdetermination\x88\x01\x01\x12\x1b\n" +
	"\x06impact\x18\f \x01(\tH\n" +
	"R\x06impact\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"version_no\x18\r \x01(\x05R\tversionNo\x12D\n" +
	"\rfollowup_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\vR\ffollowupTime\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x0f \x01(\tH\fR\bcategory\x88\x01\x01\x12%\n" +
	"\vsubcategory\x18\x10 \x01(\tH\rR\vsubcategory\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x11 \x01(\tH\x0eR\x06source\x88\x01\x01\x12$\n" +
	"\vsource_tool\x18\x12 \x01(\tH\x0fR\n" +
	"sourceTool\x88\x01\x01\x123\n" +
	"\x13source_tool_feature\x18\x13 \x01(\tH\x10R\x11sourceToolFeature\x88\x01\x01\x122\n" +
	"\x12configuration_item\x18\x14 \x01(\tH\x11R\x11configurationItem\x88\x01\x01\x12 \n" +
	"\tsoc_notes\x18\x15 \x01(\tH\x12R\bsocNotes\x88\x01\x01\x12\"\n" +
	"\n" +
	"next_steps\x18\x16 \x01(\tH\x13R\tnextSteps\x88\x01\x01\x126\n" +
	"\x14csirt_classification\x18\x17 \x01(\tH\x14R\x13csirtClassification\x88\x01\x01\x12,\n" +
	"\x10soc_lead_user_id\x18\x18 \x01(\tH\x15R\rsocLeadUserId\x88\x01\x01\x12L\n" +
	"\x11notification_time\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampH\x16R\x10notificationTime\x88\x01\x01\x124\n" +
	"\x14is_affected_user_vip\x18\x1a \x01(\bH\x17R\x11isAffectedUserVip\x88\x01\x01\x124\n" +
	"\x14requested_by_user_id\x18\x1b \x01(\tH\x18R\x11requestedByUserId\x88\x01\x01\x120\n" +
	"\x11environment_level\x18\x1c \x01(\tH\x19R\x10environmentLevel\x88\x01\x01\x12.\n" +
	"\x10environment_type\x18\x1d \x01(\tH\x1aR\x0fenvironmentType\x88\x01\x01\x12\x15\n" +
	"\x03pdn\x18\x1e \x01(\tH\x1bR\x03pdn\x88\x01\x01\x12,\n" +
	"\x0fimpacted_object\x18\x1f \x01(\tH\x1cR\x0eimpactedObject\x88\x01\x01\x12\x17\n" +
	"\x04mttr\x18  \x01(\tH\x1dR\x04mttr\x88\x01\x01\x122\n" +
	"\x12reassignment_count\x18! \x01(\x05H\x1eR\x11reassignmentCount\x88\x01\x01\x12/\n" +
	"\x11assigned_to_count\x18\" \x01(\x05H\x1fR\x0fassignedToCount\x88\x01\x01\x126\n" +
	"\x14engineering_document\x18# \x01(\tH R\x13engineeringDocument\x88\x01\x01\x120\n" +
	"\x11response_document\x18$ \x01(\tH!R\x10responseDocument\x88\x01\x01\x12*\n" +
	"\x0eclosure_reason\x18% \x01(\tH\"R\rclosureReason\x88\x01\x01\x12O\n" +
	"\x13event_occurred_time\x18& \x01(\v2\x1a.google.protobuf.TimestampH#R\x11eventOccurredTime\x88\x01\x01B\x14\n" +
	"\x12_short_descriptionB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_stateB\v\n" +
	"\t_priorityB\v\n" +
	"\t_severityB\x13\n" +
	"\x11_affected_user_idB\x13\n" +
	"\x11_assigned_user_idB\x16\n" +
	"\x14_assignment_group_idB\v\n" +
	"\t_accuracyB\x10\n" +
	"\x0e_determinationB\t\n" +
	"\a_impactB\x10\n" +
	"\x0e_followup_timeB\v\n" +
	"\t_categoryB\x0e\n" +
	"\f_subcategoryB\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_source_toolB\x16\n" +
	"\x14_source_tool_featureB\x15\n" +
	"\x13_configuration_itemB\f\n" +
	"\n" +
	"_soc_notesB\r\n" +
	"\v_next_stepsB\x17\n" +
	"\x15_csirt_classificationB\x13\n" +
	"\x11_soc_lead_user_idB\x14\n" +
	"\x12_notification_timeB\x17\n" +
	"\x15_is_affected_user_vipB\x17\n" +
	"\x15_requested_by_user_idB\x14\n" +
	"\x12_environment_levelB\x13\n" +
	"\x11_environment_typeB\x06\n" +
	"\x04_pdnB\x12\n" +
	"\x10_impacted_objectB\a\n" +
	"\x05_mttrB\x15\n" +
	"\x13_reassignment_countB\x14\n" +
	"\x12_assigned_to_countB\x17\n" +
	"\x15_engineering_documentB\x14\n" +
	"\x12_response_documentB\x11\n" +
	"\x0f_closure_reasonB\x16\n" +
	"\x14_event_occurred_time\"<\n" +
	"\x12UpdateCaseResponse\x12&\n" +
	"\x04case\x18\x01 \x01(\v2\x12.case_service.CaseR\x04case\"\xa5\x01\n" +
	"\x11AssignCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12(\n" +
	"\x10assigned_user_id\x18\x02 \x01(\tR\x0eassignedUserId\x12.\n" +
	"\x13assignment_group_id\x18\x03 \x01(\tR\x11assignmentGroupId\x12\x1d\n" +
	"\n" +
	"version_no\x18\x04 \x01(\x05R\tversionNo\"<\n" +
	"\x12AssignCaseResponse\x12&\n" +
	"\x04case\x18\x01 \x01(\v2\x12.case_service.CaseR\x04case\"\x94\x01\n" +
	"\x10CloseCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12!\n" +
	"\fclosure_code\x18\x02 \x01(\tR\vclosureCode\x12%\n" +
	"\x0eclosure_reason\x18\x03 \x01(\tR\rclosureReason\x12\x1d\n" +
	"\n" +
	"version_no\x18\x04 \x01(\x05R\tversionNo\";\n" +
	"\x11CloseCaseResponse\x12&\n" +
	"\x04case\x18\x01 \x01(\v2\x12.case_service.CaseR\x04case\"\x94\x01\n" +
	"\x12AddWorknoteRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x1b\n" +
	"\tnote_text\x18\x02 \x01(\tR\bnoteText\x12\x1b\n" +
	"\tnote_type\x18\x03 \x01(\tR\bnoteType\x12+\n" +
	"\x12created_by_user_id\x18\x04 \x01(\tR\x0fcreatedByUserId\"I\n" +
	"\x13AddWorknoteResponse\x122\n" +
	"\bworknote\x18\x01 \x01(\v2\x16.case_service.WorknoteR\bworknote\")\n" +
	"\x0eGetCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"9\n" +
	"\x0fGetCaseResponse\x12&\n" +
	"\x04case\x18\x01 \x01(\v2\x12.case_service.CaseR\x04case\"\xed\x04\n" +
	"\x10ListCasesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x19\n" +
	"\x05state\x18\x03 \x01(\tH\x00R\x05state\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\tH\x01R\bpriority\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x05 \x01(\tH\x02R\bseverity\x88\x01\x01\x123\n" +
	"\x13assignment_group_id\x18\x06 \x01(\tH\x03R\x11assignmentGroupId\x88\x01\x01\x12-\n" +
	"\x10assigned_user_id\x18\a \x01(\tH\x04R\x0eassignedUserId\x88\x01\x01\x12-\n" +
	"\x10affected_user_id\x18\b \x01(\tH\x05R\x0eaffectedUserId\x88\x01\x01\x12K\n" +
	"\x11opened_time_after\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x06R\x0fopenedTimeAfter\x88\x01\x01\x12M\n" +
	"\x12opened_time_before\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\aR\x10openedTimeBefore\x88\x01\x01B\b\n" +
	"\x06_stateB\v\n" +
	"\t_priorityB\v\n" +
	"\t_severityB\x16\n" +
	"\x14_assignment_group_idB\x13\n" +
	"\x11_assigned_user_idB\x13\n" +
	"\x11_affected_user_idB\x14\n" +
	"\x12_opened_time_afterB\x15\n" +
	"\x13_opened_time_before\"e\n" +
	"\x11ListCasesResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.case_service.CaseR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"k\n" +
	"\x14ListWorknotesRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"m\n" +
	"\x15ListWorknotesResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.case_service.WorknoteR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xae\x10\n" +
	"\x04Case\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcase_number\x18\x02 \x01(\tR\n" +
	"caseNumber\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12)\n" +
	"\x11opened_by_user_id\x18\b \x01(\tR\x0eopenedByUserId\x12;\n" +
	"\vopened_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"openedTime\x12J\n" +
	"\x13event_occurred_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x11eventOccurredTime\x12J\n" +
	"\x13event_received_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11eventReceivedTime\x12(\n" +
	"\x10affected_user_id\x18\f \x01(\tR\x0eaffectedUserId\x12(\n" +
	"\x10assigned_user_id\x18\r \x01(\tR\x0eassignedUserId\x12.\n" +
	"\x13assignment_group_id\x18\x0e \x01(\tR\x11assignmentGroupId\x12\"\n" +
	"\ralert_rule_id\x18\x0f \x01(\tR\valertRuleId\x126\n" +
	"\x17active_duration_seconds\x18\x10 \x01(\x03R\x15activeDurationSeconds\x12\x1a\n" +
	"\baccuracy\x18\x11 \x01(\tR\baccuracy\x12$\n" +
	"\rdetermination\x18\x12 \x01(\tR\rdetermination\x12\x16\n" +
	"\x06impact\x18\x13 \x01(\tR\x06impact\x12!\n" +
	"\fclosure_code\x18\x14 \x01(\tR\vclosureCode\x12%\n" +
	"\x0eclosure_reason\x18\x15 \x01(\tR\rclosureReason\x12)\n" +
	"\x11closed_by_user_id\x18\x16 \x01(\tR\x0eclosedByUserId\x12;\n" +
	"\vclosed_time\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"closedTime\x12\x1b\n" +
	"\tis_active\x18\x18 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"version_no\x18\x19 \x01(\x05R\tversionNo\x129\n" +
	"\n" +
	"created_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12?\n" +
	"\rfollowup_time\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\ffollowupTime\x12\x1a\n" +
	"\bcategory\x18\x1d \x01(\tR\bcategory\x12 \n" +
	"\vsubcategory\x18\x1e \x01(\tR\vsubcategory\x12\x16\n" +
	"\x06source\x18\x1f \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_tool\x18  \x01(\tR\n" +
	"sourceTool\x12.\n" +
	"\x13source_tool_feature\x18! \x01(\tR\x11sourceToolFeature\x12-\n" +
	"\x12configuration_item\x18\" \x01(\tR\x11configurationItem\x12\x1b\n" +
	"\tsoc_notes\x18# \x01(\tR\bsocNotes\x12\x1d\n" +
	"\n" +
	"next_steps\x18$ \x01(\tR\tnextSteps\x121\n" +
	"\x14csirt_classification\x18% \x01(\tR\x13csirtClassification\x12'\n" +
	"\x10soc_lead_user_id\x18& \x01(\tR\rsocLeadUserId\x12/\n" +
	"\x14requested_by_user_id\x18' \x01(\tR\x11requestedByUserId\x12+\n" +
	"\x11environment_level\x18( \x01(\tR\x10environmentLevel\x12)\n" +
	"\x10environment_type\x18) \x01(\tR\x0fenvironmentType\x12\x10\n" +
	"\x03pdn\x18* \x01(\tR\x03pdn\x12'\n" +
	"\x0fimpacted_object\x18+ \x01(\tR\x0eimpactedObject\x12G\n" +
	"\x11notification_time\x18, \x01(\v2\x1a.google.protobuf.TimestampR\x10notificationTime\x12\x12\n" +
	"\x04mttr\x18- \x01(\tR\x04mttr\x12-\n" +
	"\x12reassignment_count\x18. \x01(\x05R\x11reassignmentCount\x12*\n" +
	"\x11assigned_to_count\x18/ \x01(\x05R\x0fassignedToCount\x12/\n" +
	"\x14is_affected_user_vip\x180 \x01(\bR\x11isAffectedUserVip\x121\n" +
	"\x14engineering_document\x181 \x01(\tR\x13engineeringDocument\x12+\n" +
	"\x11response_document\x182 \x01(\tR\x10responseDocument\"\xaf\x02\n" +
	"\bWorknote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x1b\n" +
	"\tnote_text\x18\x03 \x01(\tR\bnoteText\x12\x1b\n" +
	"\tnote_type\x18\x04 \x01(\tR\bnoteType\x12+\n" +
	"\x12created_by_user_id\x18\x05 \x01(\tR\x0fcreatedByUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted2\x92\x05\n" +
	"\vCaseService\x12O\n" +
	"\n" +
	"CreateCase\x12\x1f.case_service.CreateCaseRequest\x1a .case_service.CreateCaseResponse\x12O\n" +
	"\n" +
	"UpdateCase\x12\x1f.case_service.UpdateCaseRequest\x1a .case_service.UpdateCaseResponse\x12O\n" +
	"\n" +
	"AssignCase\x12\x1f.case_service.AssignCaseRequest\x1a .case_service.AssignCaseResponse\x12L\n" +
	"\tCloseCase\x12\x1e.case_service.CloseCaseRequest\x1a\x1f.case_service.CloseCaseResponse\x12R\n" +
	"\vAddWorknote\x12 .case_service.AddWorknoteRequest\x1a!.case_service.AddWorknoteResponse\x12F\n" +
	"\aGetCase\x12\x1c.case_service.GetCaseRequest\x1a\x1d.case_service.GetCaseResponse\x12L\n" +
	"\tListCases\x12\x1e.case_service.ListCasesRequest\x1a\x1f.case_service.ListCasesResponse\x12X\n" +
	"\rListWorknotes\x12\".case_service.ListWorknotesRequest\x1a#.case_service.ListWorknotesResponseB7Z5github.com/servicenow/case-service/proto/case_serviceb\x06proto3"

var (
	file_proto_case_service_proto_rawDescOnce sync.Once
	file_proto_case_service_proto_rawDescData []byte
)

func file_proto_case_service_proto_rawDescGZIP() []byte {
	file_proto_case_service_proto_rawDescOnce.Do(func() {
		file_proto_case_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_case_service_proto_rawDesc), len(file_proto_case_service_proto_rawDesc)))
	})
	return file_proto_case_service_proto_rawDescData
}

var file_proto_case_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_case_service_proto_goTypes = []any{
	(*CreateCaseRequest)(nil),     // 0: case_service.CreateCaseRequest
	(*CreateCaseResponse)(nil),    // 1: case_service.CreateCaseResponse
	(*UpdateCaseRequest)(nil),     // 2: case_service.UpdateCaseRequest
	(*UpdateCaseResponse)(nil),    // 3: case_service.UpdateCaseResponse
	(*AssignCaseRequest)(nil),     // 4: case_service.AssignCaseRequest
	(*AssignCaseResponse)(nil),    // 5: case_service.AssignCaseResponse
	(*CloseCaseRequest)(nil),      // 6: case_service.CloseCaseRequest
	(*CloseCaseResponse)(nil),     // 7: case_service.CloseCaseResponse
	(*AddWorknoteRequest)(nil),    // 8: case_service.AddWorknoteRequest
	(*AddWorknoteResponse)(nil),   // 9: case_service.AddWorknoteResponse
	(*GetCaseRequest)(nil),        // 10: case_service.GetCaseRequest
	(*GetCaseResponse)(nil),       // 11: case_service.GetCaseResponse
	(*ListCasesRequest)(nil),      // 12: case_service.ListCasesRequest
	(*ListCasesResponse)(nil),     // 13: case_service.ListCasesResponse
	(*ListWorknotesRequest)(nil),  // 14: case_service.ListWorknotesRequest
	(*ListWorknotesResponse)(nil), // 15: case_service.ListWorknotesResponse
	(*Case)(nil),                  // 16: case_service.Case
	(*Worknote)(nil),              // 17: case_service.Worknote
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_proto_case_service_proto_depIdxs = []int32{
	18, // 0: case_service.CreateCaseRequest.opened_time:type_name -> google.protobuf.Timestamp
	18, // 1: case_service.CreateCaseRequest.event_occurred_time:type_name -> google.protobuf.Timestamp
	18, // 2: case_service.CreateCaseRequest.event_received_time:type_name -> google.protobuf.Timestamp
	18, // 3: case_service.CreateCaseRequest.followup_time:type_name -> google.protobuf.Timestamp
	18, // 4: case_service.CreateCaseRequest.notification_time:type_name -> google.protobuf.Timestamp
	18, // 5: case_service.UpdateCaseRequest.followup_time:type_name -> google.protobuf.Timestamp
	18, // 6: case_service.UpdateCaseRequest.notification_time:type_name -> google.protobuf.Timestamp
	18, // 7: case_service.UpdateCaseRequest.event_occurred_time:type_name -> google.protobuf.Timestamp
	16, // 8: case_service.UpdateCaseResponse.case:type_name -> case_service.Case
	16, // 9: case_service.AssignCaseResponse.case:type_name -> case_service.Case
	16, // 10: case_service.CloseCaseResponse.case:type_name -> case_service.Case
	17, // 11: case_service.AddWorknoteResponse.worknote:type_name -> case_service.Worknote
	16, // 12: case_service.GetCaseResponse.case:type_name -> case_service.Case
	18, // 13: case_service.ListCasesRequest.opened_time_after:type_name -> google.protobuf.Timestamp
	18, // 14: case_service.ListCasesRequest.opened_time_before:type_name -> google.protobuf.Timestamp
	16, // 15: case_service.ListCasesResponse.items:type_name -> case_service.Case
	17, // 16: case_service.ListWorknotesResponse.items:type_name -> case_service.Worknote
	18, // 17: case_service.Case.opened_time:type_name -> google.protobuf.Timestamp
	18, // 18: case_service.Case.event_occurred_time:type_name -> google.protobuf.Timestamp
	18, // 19: case_service.Case.event_received_time:type_name -> google.protobuf.Timestamp
	18, // 20: case_service.Case.closed_time:type_name -> google.protobuf.Timestamp
	18, // 21: case_service.Case.created_at:type_name -> google.protobuf.Timestamp
	18, // 22: case_service.Case.updated_at:type_name -> google.protobuf.Timestamp
	18, // 23: case_service.Case.followup_time:type_name -> google.protobuf.Timestamp
	18, // 24: case_service.Case.notification_time:type_name -> google.protobuf.Timestamp
	18, // 25: case_service.Worknote.created_at:type_name -> google.protobuf.Timestamp
	18, // 26: case_service.Worknote.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 27: case_service.CaseService.CreateCase:input_type -> case_service.CreateCaseRequest
	2,  // 28: case_service.CaseService.UpdateCase:input_type -> case_service.UpdateCaseRequest
	4,  // 29: case_service.CaseService.AssignCase:input_type -> case_service.AssignCaseRequest
	6,  // 30: case_service.CaseService.CloseCase:input_type -> case_service.CloseCaseRequest
	8,  // 31: case_service.CaseService.AddWorknote:input_type -> case_service.AddWorknoteRequest
	10, // 32: case_service.CaseService.GetCase:input_type -> case_service.GetCaseRequest
	12, // 33: case_service.CaseService.ListCases:input_type -> case_service.ListCasesRequest
	14, // 34: case_service.CaseService.ListWorknotes:input_type -> case_service.ListWorknotesRequest
	1,  // 35: case_service.CaseService.CreateCase:output_type -> case_service.CreateCaseResponse
	3,  // 36: case_service.CaseService.UpdateCase:output_type -> case_service.UpdateCaseResponse
	5,  // 37: case_service.CaseService.AssignCase:output_type -> case_service.AssignCaseResponse
	7,  // 38: case_service.CaseService.CloseCase:output_type -> case_service.CloseCaseResponse
	9,  // 39: case_service.CaseService.AddWorknote:output_type -> case_service.AddWorknoteResponse
	11, // 40: case_service.CaseService.GetCase:output_type -> case_service.GetCaseResponse
	13, // 41: case_service.CaseService.ListCases:output_type -> case_service.ListCasesResponse
	15, // 42: case_service.CaseService.ListWorknotes:output_type -> case_service.ListWorknotesResponse
	35, // [35:43] is the sub-list for method output_type
	27, // [27:35] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_case_service_proto_init() }
func file_proto_case_service_proto_init() {
	if File_proto_case_service_proto != nil {
		return
	}
	file_proto_case_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_case_service_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_case_service_proto_rawDesc), len(file_proto_case_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_case_service_proto_goTypes,
		DependencyIndexes: file_proto_case_service_proto_depIdxs,
		MessageInfos:      file_proto_case_service_proto_msgTypes,
	}.Build()
	File_proto_case_service_proto = out.File
	file_proto_case_service_proto_goTypes = nil
	file_proto_case_service_proto_depIdxs = nil
}
