// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: proto/case_service.proto

package case_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaseService_CreateCase_FullMethodName    = "/case_service.CaseService/CreateCase"
	CaseService_UpdateCase_FullMethodName    = "/case_service.CaseService/UpdateCase"
	CaseService_AssignCase_FullMethodName    = "/case_service.CaseService/AssignCase"
	CaseService_CloseCase_FullMethodName     = "/case_service.CaseService/CloseCase"
	CaseService_AddWorknote_FullMethodName   = "/case_service.CaseService/AddWorknote"
	CaseService_GetCase_FullMethodName       = "/case_service.CaseService/GetCase"
	CaseService_ListCases_FullMethodName     = "/case_service.CaseService/ListCases"
	CaseService_ListWorknotes_FullMethodName = "/case_service.CaseService/ListWorknotes"
)

// CaseServiceClient is the client API for CaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaseServiceClient interface {
	CreateCase(ctx context.Context, in *CreateCaseRequest, opts ...grpc.CallOption) (*CreateCaseResponse, error)
	UpdateCase(ctx context.Context, in *UpdateCaseRequest, opts ...grpc.CallOption) (*UpdateCaseResponse, error)
	AssignCase(ctx context.Context, in *AssignCaseRequest, opts ...grpc.CallOption) (*AssignCaseResponse, error)
	CloseCase(ctx context.Context, in *CloseCaseRequest, opts ...grpc.CallOption) (*CloseCaseResponse, error)
	AddWorknote(ctx context.Context, in *AddWorknoteRequest, opts ...grpc.CallOption) (*AddWorknoteResponse, error)
	GetCase(ctx context.Context, in *GetCaseRequest, opts ...grpc.CallOption) (*GetCaseResponse, error)
	ListCases(ctx context.Context, in *ListCasesRequest, opts ...grpc.CallOption) (*ListCasesResponse, error)
	ListWorknotes(ctx context.Context, in *ListWorknotesRequest, opts ...grpc.CallOption) (*ListWorknotesResponse, error)
}

type caseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaseServiceClient(cc grpc.ClientConnInterface) CaseServiceClient {
	return &caseServiceClient{cc}
}

func (c *caseServiceClient) CreateCase(ctx context.Context, in *CreateCaseRequest, opts ...grpc.CallOption) (*CreateCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCaseResponse)
	err := c.cc.Invoke(ctx, CaseService_CreateCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) UpdateCase(ctx context.Context, in *UpdateCaseRequest, opts ...grpc.CallOption) (*UpdateCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCaseResponse)
	err := c.cc.Invoke(ctx, CaseService_UpdateCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) AssignCase(ctx context.Context, in *AssignCaseRequest, opts ...grpc.CallOption) (*AssignCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignCaseResponse)
	err := c.cc.Invoke(ctx, CaseService_AssignCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) CloseCase(ctx context.Context, in *CloseCaseRequest, opts ...grpc.CallOption) (*CloseCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseCaseResponse)
	err := c.cc.Invoke(ctx, CaseService_CloseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) AddWorknote(ctx context.Context, in *AddWorknoteRequest, opts ...grpc.CallOption) (*AddWorknoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWorknoteResponse)
	err := c.cc.Invoke(ctx, CaseService_AddWorknote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) GetCase(ctx context.Context, in *GetCaseRequest, opts ...grpc.CallOption) (*GetCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaseResponse)
	err := c.cc.Invoke(ctx, CaseService_GetCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) ListCases(ctx context.Context, in *ListCasesRequest, opts ...grpc.CallOption) (*ListCasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCasesResponse)
	err := c.cc.Invoke(ctx, CaseService_ListCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caseServiceClient) ListWorknotes(ctx context.Context, in *ListWorknotesRequest, opts ...grpc.CallOption) (*ListWorknotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorknotesResponse)
	err := c.cc.Invoke(ctx, CaseService_ListWorknotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaseServiceServer is the server API for CaseService service.
// All implementations must embed UnimplementedCaseServiceServer
// for forward compatibility.
type CaseServiceServer interface {
	CreateCase(context.Context, *CreateCaseRequest) (*CreateCaseResponse, error)
	UpdateCase(context.Context, *UpdateCaseRequest) (*UpdateCaseResponse, error)
	AssignCase(context.Context, *AssignCaseRequest) (*AssignCaseResponse, error)
	CloseCase(context.Context, *CloseCaseRequest) (*CloseCaseResponse, error)
	AddWorknote(context.Context, *AddWorknoteRequest) (*AddWorknoteResponse, error)
	GetCase(context.Context, *GetCaseRequest) (*GetCaseResponse, error)
	ListCases(context.Context, *ListCasesRequest) (*ListCasesResponse, error)
	ListWorknotes(context.Context, *ListWorknotesRequest) (*ListWorknotesResponse, error)
	mustEmbedUnimplementedCaseServiceServer()
}

// UnimplementedCaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaseServiceServer struct{}

func (UnimplementedCaseServiceServer) CreateCase(context.Context, *CreateCaseRequest) (*CreateCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCase not implemented")
}
func (UnimplementedCaseServiceServer) UpdateCase(context.Context, *UpdateCaseRequest) (*UpdateCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCase not implemented")
}
func (UnimplementedCaseServiceServer) AssignCase(context.Context, *AssignCaseRequest) (*AssignCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCase not implemented")
}
func (UnimplementedCaseServiceServer) CloseCase(context.Context, *CloseCaseRequest) (*CloseCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseCase not implemented")
}
func (UnimplementedCaseServiceServer) AddWorknote(context.Context, *AddWorknoteRequest) (*AddWorknoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWorknote not implemented")
}
func (UnimplementedCaseServiceServer) GetCase(context.Context, *GetCaseRequest) (*GetCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCase not implemented")
}
func (UnimplementedCaseServiceServer) ListCases(context.Context, *ListCasesRequest) (*ListCasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCases not implemented")
}
func (UnimplementedCaseServiceServer) ListWorknotes(context.Context, *ListWorknotesRequest) (*ListWorknotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorknotes not implemented")
}
func (UnimplementedCaseServiceServer) mustEmbedUnimplementedCaseServiceServer() {}
func (UnimplementedCaseServiceServer) testEmbeddedByValue()                     {}

// UnsafeCaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaseServiceServer will
// result in compilation errors.
type UnsafeCaseServiceServer interface {
	mustEmbedUnimplementedCaseServiceServer()
}

func RegisterCaseServiceServer(s grpc.ServiceRegistrar, srv CaseServiceServer) {
	// If the following call panics, it indicates UnimplementedCaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaseService_ServiceDesc, srv)
}

func _CaseService_CreateCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).CreateCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_CreateCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).CreateCase(ctx, req.(*CreateCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_UpdateCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).UpdateCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_UpdateCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).UpdateCase(ctx, req.(*UpdateCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_AssignCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).AssignCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_AssignCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).AssignCase(ctx, req.(*AssignCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_CloseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).CloseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_CloseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).CloseCase(ctx, req.(*CloseCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_AddWorknote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorknoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).AddWorknote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_AddWorknote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).AddWorknote(ctx, req.(*AddWorknoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_GetCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).GetCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_GetCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).GetCase(ctx, req.(*GetCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_ListCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).ListCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_ListCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).ListCases(ctx, req.(*ListCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaseService_ListWorknotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorknotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseServiceServer).ListWorknotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaseService_ListWorknotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseServiceServer).ListWorknotes(ctx, req.(*ListWorknotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaseService_ServiceDesc is the grpc.ServiceDesc for CaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "case_service.CaseService",
	HandlerType: (*CaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCase",
			Handler:    _CaseService_CreateCase_Handler,
		},
		{
			MethodName: "UpdateCase",
			Handler:    _CaseService_UpdateCase_Handler,
		},
		{
			MethodName: "AssignCase",
			Handler:    _CaseService_AssignCase_Handler,
		},
		{
			MethodName: "CloseCase",
			Handler:    _CaseService_CloseCase_Handler,
		},
		{
			MethodName: "AddWorknote",
			Handler:    _CaseService_AddWorknote_Handler,
		},
		{
			MethodName: "GetCase",
			Handler:    _CaseService_GetCase_Handler,
		},
		{
			MethodName: "ListCases",
			Handler:    _CaseService_ListCases_Handler,
		},
		{
			MethodName: "ListWorknotes",
			Handler:    _CaseService_ListWorknotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/case_service.proto",
}
