// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: audit_service.proto

package audit_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_IngestEvent_FullMethodName                    = "/audit_service.AuditService/IngestEvent"
	AuditService_ListAuditEventsByCase_FullMethodName          = "/audit_service.AuditService/ListAuditEventsByCase"
	AuditService_ListAuditEventsByObservable_FullMethodName    = "/audit_service.AuditService/ListAuditEventsByObservable"
	AuditService_ListAuditEventsByEntity_FullMethodName        = "/audit_service.AuditService/ListAuditEventsByEntity"
	AuditService_ListAuditEventsByActor_FullMethodName         = "/audit_service.AuditService/ListAuditEventsByActor"
	AuditService_ListAuditEventsByCorrelationId_FullMethodName = "/audit_service.AuditService/ListAuditEventsByCorrelationId"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error)
	ListAuditEventsByCase(ctx context.Context, in *ListAuditEventsByCaseRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
	ListAuditEventsByObservable(ctx context.Context, in *ListAuditEventsByObservableRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
	ListAuditEventsByEntity(ctx context.Context, in *ListAuditEventsByEntityRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
	ListAuditEventsByActor(ctx context.Context, in *ListAuditEventsByActorRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
	ListAuditEventsByCorrelationId(ctx context.Context, in *ListAuditEventsByCorrelationIdRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEventResponse)
	err := c.cc.Invoke(ctx, AuditService_IngestEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditEventsByCase(ctx context.Context, in *ListAuditEventsByCaseRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEventsByCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditEventsByObservable(ctx context.Context, in *ListAuditEventsByObservableRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEventsByObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditEventsByEntity(ctx context.Context, in *ListAuditEventsByEntityRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEventsByEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditEventsByActor(ctx context.Context, in *ListAuditEventsByActorRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEventsByActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditEventsByCorrelationId(ctx context.Context, in *ListAuditEventsByCorrelationIdRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEventsByCorrelationId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	ListAuditEventsByCase(context.Context, *ListAuditEventsByCaseRequest) (*ListAuditEventsResponse, error)
	ListAuditEventsByObservable(context.Context, *ListAuditEventsByObservableRequest) (*ListAuditEventsResponse, error)
	ListAuditEventsByEntity(context.Context, *ListAuditEventsByEntityRequest) (*ListAuditEventsResponse, error)
	ListAuditEventsByActor(context.Context, *ListAuditEventsByActorRequest) (*ListAuditEventsResponse, error)
	ListAuditEventsByCorrelationId(context.Context, *ListAuditEventsByCorrelationIdRequest) (*ListAuditEventsResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestEvent not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditEventsByCase(context.Context, *ListAuditEventsByCaseRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEventsByCase not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditEventsByObservable(context.Context, *ListAuditEventsByObservableRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEventsByObservable not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditEventsByEntity(context.Context, *ListAuditEventsByEntityRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEventsByEntity not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditEventsByActor(context.Context, *ListAuditEventsByActorRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEventsByActor not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditEventsByCorrelationId(context.Context, *ListAuditEventsByCorrelationIdRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEventsByCorrelationId not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_IngestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).IngestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_IngestEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).IngestEvent(ctx, req.(*IngestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditEventsByCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsByCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEventsByCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEventsByCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEventsByCase(ctx, req.(*ListAuditEventsByCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditEventsByObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsByObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEventsByObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEventsByObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEventsByObservable(ctx, req.(*ListAuditEventsByObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditEventsByEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsByEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEventsByEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEventsByEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEventsByEntity(ctx, req.(*ListAuditEventsByEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditEventsByActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsByActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEventsByActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEventsByActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEventsByActor(ctx, req.(*ListAuditEventsByActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditEventsByCorrelationId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsByCorrelationIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEventsByCorrelationId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEventsByCorrelationId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEventsByCorrelationId(ctx, req.(*ListAuditEventsByCorrelationIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit_service.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestEvent",
			Handler:    _AuditService_IngestEvent_Handler,
		},
		{
			MethodName: "ListAuditEventsByCase",
			Handler:    _AuditService_ListAuditEventsByCase_Handler,
		},
		{
			MethodName: "ListAuditEventsByObservable",
			Handler:    _AuditService_ListAuditEventsByObservable_Handler,
		},
		{
			MethodName: "ListAuditEventsByEntity",
			Handler:    _AuditService_ListAuditEventsByEntity_Handler,
		},
		{
			MethodName: "ListAuditEventsByActor",
			Handler:    _AuditService_ListAuditEventsByActor_Handler,
		},
		{
			MethodName: "ListAuditEventsByCorrelationId",
			Handler:    _AuditService_ListAuditEventsByCorrelationId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit_service.proto",
}
