// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: audit_service.proto

package audit_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEventRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type IngestEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingested      bool                   `protobuf:"varint,1,opt,name=ingested,proto3" json:"ingested,omitempty"` // true if newly stored, false if duplicate event_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventResponse) GetIngested() bool {
	if x != nil {
		return x.Ingested
	}
	return false
}

type ListAuditEventsByCaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CaseId         string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OccurredAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_after,json=occurredAfter,proto3,oneof" json:"occurred_after,omitempty"`
	OccurredBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_before,json=occurredBefore,proto3,oneof" json:"occurred_before,omitempty"`
	OldestFirst    bool                   `protobuf:"varint,6,opt,name=oldest_first,json=oldestFirst,proto3" json:"oldest_first,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditEventsByCaseRequest) Reset() {
	*x = ListAuditEventsByCaseRequest{}
	mi := &file_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsByCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsByCaseRequest) ProtoMessage() {}

func (x *ListAuditEventsByCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsByCaseRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsByCaseRequest) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuditEventsByCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ListAuditEventsByCaseRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditEventsByCaseRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditEventsByCaseRequest) GetOccurredAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAfter
	}
	return nil
}

func (x *ListAuditEventsByCaseRequest) GetOccurredBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredBefore
	}
	return nil
}

func (x *ListAuditEventsByCaseRequest) GetOldestFirst() bool {
	if x != nil {
		return x.OldestFirst
	}
	return false
}

type ListAuditEventsByObservableRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObservableId   string                 `protobuf:"bytes,1,opt,name=observable_id,json=observableId,proto3" json:"observable_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OccurredAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_after,json=occurredAfter,proto3,oneof" json:"occurred_after,omitempty"`
	OccurredBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_before,json=occurredBefore,proto3,oneof" json:"occurred_before,omitempty"`
	OldestFirst    bool                   `protobuf:"varint,6,opt,name=oldest_first,json=oldestFirst,proto3" json:"oldest_first,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditEventsByObservableRequest) Reset() {
	*x = ListAuditEventsByObservableRequest{}
	mi := &file_audit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsByObservableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsByObservableRequest) ProtoMessage() {}

func (x *ListAuditEventsByObservableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsByObservableRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsByObservableRequest) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuditEventsByObservableRequest) GetObservableId() string {
	if x != nil {
		return x.ObservableId
	}
	return ""
}

func (x *ListAuditEventsByObservableRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditEventsByObservableRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditEventsByObservableRequest) GetOccurredAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAfter
	}
	return nil
}

func (x *ListAuditEventsByObservableRequest) GetOccurredBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredBefore
	}
	return nil
}

func (x *ListAuditEventsByObservableRequest) GetOldestFirst() bool {
	if x != nil {
		return x.OldestFirst
	}
	return false
}

type ListAuditEventsByEntityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityType     string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId       string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OccurredAfter  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_after,json=occurredAfter,proto3,oneof" json:"occurred_after,omitempty"`
	OccurredBefore *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_before,json=occurredBefore,proto3,oneof" json:"occurred_before,omitempty"`
	OldestFirst    bool                   `protobuf:"varint,7,opt,name=oldest_first,json=oldestFirst,proto3" json:"oldest_first,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditEventsByEntityRequest) Reset() {
	*x = ListAuditEventsByEntityRequest{}
	mi := &file_audit_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsByEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsByEntityRequest) ProtoMessage() {}

func (x *ListAuditEventsByEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsByEntityRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsByEntityRequest) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAuditEventsByEntityRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListAuditEventsByEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ListAuditEventsByEntityRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditEventsByEntityRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditEventsByEntityRequest) GetOccurredAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAfter
	}
	return nil
}

func (x *ListAuditEventsByEntityRequest) GetOccurredBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredBefore
	}
	return nil
}

func (x *ListAuditEventsByEntityRequest) GetOldestFirst() bool {
	if x != nil {
		return x.OldestFirst
	}
	return false
}

type ListAuditEventsByActorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId    string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OccurredAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_after,json=occurredAfter,proto3,oneof" json:"occurred_after,omitempty"`
	OccurredBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_before,json=occurredBefore,proto3,oneof" json:"occurred_before,omitempty"`
	OldestFirst    bool                   `protobuf:"varint,6,opt,name=oldest_first,json=oldestFirst,proto3" json:"oldest_first,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditEventsByActorRequest) Reset() {
	*x = ListAuditEventsByActorRequest{}
	mi := &file_audit_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsByActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsByActorRequest) ProtoMessage() {}

func (x *ListAuditEventsByActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsByActorRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsByActorRequest) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuditEventsByActorRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *ListAuditEventsByActorRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditEventsByActorRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditEventsByActorRequest) GetOccurredAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAfter
	}
	return nil
}

func (x *ListAuditEventsByActorRequest) GetOccurredBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredBefore
	}
	return nil
}

func (x *ListAuditEventsByActorRequest) GetOldestFirst() bool {
	if x != nil {
		return x.OldestFirst
	}
	return false
}

type ListAuditEventsByCorrelationIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OccurredAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_after,json=occurredAfter,proto3,oneof" json:"occurred_after,omitempty"`
	OccurredBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_before,json=occurredBefore,proto3,oneof" json:"occurred_before,omitempty"`
	OldestFirst    bool                   `protobuf:"varint,6,opt,name=oldest_first,json=oldestFirst,proto3" json:"oldest_first,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditEventsByCorrelationIdRequest) Reset() {
	*x = ListAuditEventsByCorrelationIdRequest{}
	mi := &file_audit_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsByCorrelationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsByCorrelationIdRequest) ProtoMessage() {}

func (x *ListAuditEventsByCorrelationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsByCorrelationIdRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsByCorrelationIdRequest) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuditEventsByCorrelationIdRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ListAuditEventsByCorrelationIdRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditEventsByCorrelationIdRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditEventsByCorrelationIdRequest) GetOccurredAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAfter
	}
	return nil
}

func (x *ListAuditEventsByCorrelationIdRequest) GetOccurredBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredBefore
	}
	return nil
}

func (x *ListAuditEventsByCorrelationIdRequest) GetOldestFirst() bool {
	if x != nil {
		return x.OldestFirst
	}
	return false
}

type ListAuditEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AuditEvent          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEventsResponse) Reset() {
	*x = ListAuditEventsResponse{}
	mi := &file_audit_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsResponse) ProtoMessage() {}

func (x *ListAuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListAuditEventsResponse) GetItems() []*AuditEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAuditEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AuditEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SourceService    string                 `protobuf:"bytes,4,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	EntityType       string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId         string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ParentEntityType string                 `protobuf:"bytes,7,opt,name=parent_entity_type,json=parentEntityType,proto3" json:"parent_entity_type,omitempty"`
	ParentEntityId   string                 `protobuf:"bytes,8,opt,name=parent_entity_id,json=parentEntityId,proto3" json:"parent_entity_id,omitempty"`
	CaseId           string                 `protobuf:"bytes,9,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	ObservableId     string                 `protobuf:"bytes,10,opt,name=observable_id,json=observableId,proto3" json:"observable_id,omitempty"`
	Action           string                 `protobuf:"bytes,11,opt,name=action,proto3" json:"action,omitempty"`
	ActorUserId      string                 `protobuf:"bytes,12,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	ActorName        string                 `protobuf:"bytes,13,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	RequestId        string                 `protobuf:"bytes,14,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,15,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ChangeSummary    string                 `protobuf:"bytes,16,opt,name=change_summary,json=changeSummary,proto3" json:"change_summary,omitempty"`
	BeforeDataJson   string                 `protobuf:"bytes,17,opt,name=before_data_json,json=beforeDataJson,proto3" json:"before_data_json,omitempty"`
	AfterDataJson    string                 `protobuf:"bytes,18,opt,name=after_data_json,json=afterDataJson,proto3" json:"after_data_json,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,19,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	IngestedAt       *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_audit_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_audit_service_proto_rawDescGZIP(), []int{8}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *AuditEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditEvent) GetParentEntityType() string {
	if x != nil {
		return x.ParentEntityType
	}
	return ""
}

func (x *AuditEvent) GetParentEntityId() string {
	if x != nil {
		return x.ParentEntityId
	}
	return ""
}

func (x *AuditEvent) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *AuditEvent) GetObservableId() string {
	if x != nil {
		return x.ObservableId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *AuditEvent) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEvent) GetChangeSummary() string {
	if x != nil {
		return x.ChangeSummary
	}
	return ""
}

func (x *AuditEvent) GetBeforeDataJson() string {
	if x != nil {
		return x.BeforeDataJson
	}
	return ""
}

func (x *AuditEvent) GetAfterDataJson() string {
	if x != nil {
		return x.AfterDataJson
	}
	return ""
}

func (x *AuditEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *AuditEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuditEvent) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

var File_audit_service_proto protoreflect.FileDescriptor

const file_audit_service_proto_rawDesc = "" +
	"\n" +
	"\x13audit_service.proto\x12\raudit_service\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x12IngestEventRequest\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.audit_service.AuditEventR\x05event\"1\n" +
	"\x13IngestEventResponse\x12\x1a\n" +
	"\bingested\x18\x01 \x01(\bR\bingested\"\xcf\x02\n" +
	"\x1cListAuditEventsByCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12F\n" +
	"\x0eoccurred_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\roccurredAfter\x88\x01\x01\x12H\n" +
	"\x0foccurred_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eoccurredBefore\x88\x01\x01\x12!\n" +
	"\foldest_first\x18\x06 \x01(\bR\voldestFirstB\x11\n" +
	"\x0f_occurred_afterB\x12\n" +
	"\x10_occurred_before\"\xe1\x02\n" +
	"\"ListAuditEventsByObservableRequest\x12#\n" +
	"\robservable_id\x18\x01 \x01(\tR\fobservableId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12F\n" +
	"\x0eoccurred_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\roccurredAfter\x88\x01\x01\x12H\n" +
	"\x0foccurred_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eoccurredBefore\x88\x01\x01\x12!\n" +
	"\foldest_first\x18\x06 \x01(\bR\voldestFirstB\x11\n" +
	"\x0f_occurred_afterB\x12\n" +
	"\x10_occurred_before\"\xf6\x02\n" +
	"\x1eListAuditEventsByEntityRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12F\n" +
	"\x0eoccurred_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\roccurredAfter\x88\x01\x01\x12H\n" +
	"\x0foccurred_before\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eoccurredBefore\x88\x01\x01\x12!\n" +
	"\foldest_first\x18\a \x01(\bR\voldestFirstB\x11\n" +
	"\x0f_occurred_afterB\x12\n" +
	"\x10_occurred_before\"\xdb\x02\n" +
	"\x1dListAuditEventsByActorRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12F\n" +
	"\x0eoccurred_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\roccurredAfter\x88\x01\x01\x12H\n" +
	"\x0foccurred_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eoccurredBefore\x88\x01\x01\x12!\n" +
	"\foldest_first\x18\x06 \x01(\bR\voldestFirstB\x11\n" +
	"\x0f_occurred_afterB\x12\n" +
	"\x10_occurred_before\"\xe6\x02\n" +
	"%ListAuditEventsByCorrelationIdRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12F\n" +
	"\x0eoccurred_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\roccurredAfter\x88\x01\x01\x12H\n" +
	"\x0foccurred_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eoccurredBefore\x88\x01\x01\x12!\n" +
	"\foldest_first\x18\x06 \x01(\bR\voldestFirstB\x11\n" +
	"\x0f_occurred_afterB\x12\n" +
	"\x10_occurred_before\"r\n" +
	"\x17ListAuditEventsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.audit_service.AuditEventR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8a\x06\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12%\n" +
	"\x0esource_service\x18\x04 \x01(\tR\rsourceService\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12,\n" +
	"\x12parent_entity_type\x18\a \x01(\tR\x10parentEntityType\x12(\n" +
	"\x10parent_entity_id\x18\b \x01(\tR\x0eparentEntityId\x12\x17\n" +
	"\acase_id\x18\t \x01(\tR\x06caseId\x12#\n" +
	"\robservable_id\x18\n" +
	" \x01(\tR\fobservableId\x12\x16\n" +
	"\x06action\x18\v \x01(\tR\x06action\x12\"\n" +
	"\ractor_user_id\x18\f \x01(\tR\vactorUserId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\r \x01(\tR\tactorName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x0e \x01(\tR\trequestId\x12%\n" +
	"\x0ecorrelation_id\x18\x0f \x01(\tR\rcorrelationId\x12%\n" +
	"\x0echange_summary\x18\x10 \x01(\tR\rchangeSummary\x12(\n" +
	"\x10before_data_json\x18\x11 \x01(\tR\x0ebeforeDataJson\x12&\n" +
	"\x0fafter_data_json\x18\x12 \x01(\tR\rafterDataJson\x12#\n" +
	"\rmetadata_json\x18\x13 \x01(\tR\fmetadataJson\x12;\n" +
	"\voccurred_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12;\n" +
	"\vingested_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestedAt2\xae\x05\n" +
	"\fAuditService\x12T\n" +
	"\vIngestEvent\x12!.audit_service.IngestEventRequest\x1a\".audit_service.IngestEventResponse\x12l\n" +
	"\x15ListAuditEventsByCase\x12+.audit_service.ListAuditEventsByCaseRequest\x1a&.audit_service.ListAuditEventsResponse\x12x\n" +
	"\x1bListAuditEventsByObservable\x121.audit_service.ListAuditEventsByObservableRequest\x1a&.audit_service.ListAuditEventsResponse\x12p\n" +
	"\x17ListAuditEventsByEntity\x12-.audit_service.ListAuditEventsByEntityRequest\x1a&.audit_service.ListAuditEventsResponse\x12n\n" +
	"\x16ListAuditEventsByActor\x12,.audit_service.ListAuditEventsByActorRequest\x1a&.audit_service.ListAuditEventsResponse\x12~\n" +
	"\x1eListAuditEventsByCorrelationId\x124.audit_service.ListAuditEventsByCorrelationIdRequest\x1a&.audit_service.ListAuditEventsResponseB9Z7github.com/servicenow/audit-service/proto/audit_serviceb\x06proto3"

var (
	file_audit_service_proto_rawDescOnce sync.Once
	file_audit_service_proto_rawDescData []byte
)

func file_audit_service_proto_rawDescGZIP() []byte {
	file_audit_service_proto_rawDescOnce.Do(func() {
		file_audit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_service_proto_rawDesc), len(file_audit_service_proto_rawDesc)))
	})
	return file_audit_service_proto_rawDescData
}

var file_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_audit_service_proto_goTypes = []any{
	(*IngestEventRequest)(nil),                    // 0: audit_service.IngestEventRequest
	(*IngestEventResponse)(nil),                   // 1: audit_service.IngestEventResponse
	(*ListAuditEventsByCaseRequest)(nil),          // 2: audit_service.ListAuditEventsByCaseRequest
	(*ListAuditEventsByObservableRequest)(nil),    // 3: audit_service.ListAuditEventsByObservableRequest
	(*ListAuditEventsByEntityRequest)(nil),        // 4: audit_service.ListAuditEventsByEntityRequest
	(*ListAuditEventsByActorRequest)(nil),         // 5: audit_service.ListAuditEventsByActorRequest
	(*ListAuditEventsByCorrelationIdRequest)(nil), // 6: audit_service.ListAuditEventsByCorrelationIdRequest
	(*ListAuditEventsResponse)(nil),               // 7: audit_service.ListAuditEventsResponse
	(*AuditEvent)(nil),                            // 8: audit_service.AuditEvent
	(*timestamppb.Timestamp)(nil),                 // 9: google.protobuf.Timestamp
}
var file_audit_service_proto_depIdxs = []int32{
	8,  // 0: audit_service.IngestEventRequest.event:type_name -> audit_service.AuditEvent
	9,  // 1: audit_service.ListAuditEventsByCaseRequest.occurred_after:type_name -> google.protobuf.Timestamp
	9,  // 2: audit_service.ListAuditEventsByCaseRequest.occurred_before:type_name -> google.protobuf.Timestamp
	9,  // 3: audit_service.ListAuditEventsByObservableRequest.occurred_after:type_name -> google.protobuf.Timestamp
	9,  // 4: audit_service.ListAuditEventsByObservableRequest.occurred_before:type_name -> google.protobuf.Timestamp
	9,  // 5: audit_service.ListAuditEventsByEntityRequest.occurred_after:type_name -> google.protobuf.Timestamp
	9,  // 6: audit_service.ListAuditEventsByEntityRequest.occurred_before:type_name -> google.protobuf.Timestamp
	9,  // 7: audit_service.ListAuditEventsByActorRequest.occurred_after:type_name -> google.protobuf.Timestamp
	9,  // 8: audit_service.ListAuditEventsByActorRequest.occurred_before:type_name -> google.protobuf.Timestamp
	9,  // 9: audit_service.ListAuditEventsByCorrelationIdRequest.occurred_after:type_name -> google.protobuf.Timestamp
	9,  // 10: audit_service.ListAuditEventsByCorrelationIdRequest.occurred_before:type_name -> google.protobuf.Timestamp
	8,  // 11: audit_service.ListAuditEventsResponse.items:type_name -> audit_service.AuditEvent
	9,  // 12: audit_service.AuditEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 13: audit_service.AuditEvent.ingested_at:type_name -> google.protobuf.Timestamp
	0,  // 14: audit_service.AuditService.IngestEvent:input_type -> audit_service.IngestEventRequest
	2,  // 15: audit_service.AuditService.ListAuditEventsByCase:input_type -> audit_service.ListAuditEventsByCaseRequest
	3,  // 16: audit_service.AuditService.ListAuditEventsByObservable:input_type -> audit_service.ListAuditEventsByObservableRequest
	4,  // 17: audit_service.AuditService.ListAuditEventsByEntity:input_type -> audit_service.ListAuditEventsByEntityRequest
	5,  // 18: audit_service.AuditService.ListAuditEventsByActor:input_type -> audit_service.ListAuditEventsByActorRequest
	6,  // 19: audit_service.AuditService.ListAuditEventsByCorrelationId:input_type -> audit_service.ListAuditEventsByCorrelationIdRequest
	1,  // 20: audit_service.AuditService.IngestEvent:output_type -> audit_service.IngestEventResponse
	7,  // 21: audit_service.AuditService.ListAuditEventsByCase:output_type -> audit_service.ListAuditEventsResponse
	7,  // 22: audit_service.AuditService.ListAuditEventsByObservable:output_type -> audit_service.ListAuditEventsResponse
	7,  // 23: audit_service.AuditService.ListAuditEventsByEntity:output_type -> audit_service.ListAuditEventsResponse
	7,  // 24: audit_service.AuditService.ListAuditEventsByActor:output_type -> audit_service.ListAuditEventsResponse
	7,  // 25: audit_service.AuditService.ListAuditEventsByCorrelationId:output_type -> audit_service.ListAuditEventsResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_audit_service_proto_init() }
func file_audit_service_proto_init() {
	if File_audit_service_proto != nil {
		return
	}
	file_audit_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_audit_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_audit_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_audit_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_audit_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_service_proto_rawDesc), len(file_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_service_proto_goTypes,
		DependencyIndexes: file_audit_service_proto_depIdxs,
		MessageInfos:      file_audit_service_proto_msgTypes,
	}.Build()
	File_audit_service_proto = out.File
	file_audit_service_proto_goTypes = nil
	file_audit_service_proto_depIdxs = nil
}
