// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: proto/alert_observable_service.proto

package alert_observable_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertObservableService_CreateAlertRule_FullMethodName                  = "/alert_observable_service.AlertObservableService/CreateAlertRule"
	AlertObservableService_CreateAlert_FullMethodName                      = "/alert_observable_service.AlertObservableService/CreateAlert"
	AlertObservableService_CreateOrGetObservable_FullMethodName            = "/alert_observable_service.AlertObservableService/CreateOrGetObservable"
	AlertObservableService_LinkObservableToCase_FullMethodName             = "/alert_observable_service.AlertObservableService/LinkObservableToCase"
	AlertObservableService_UpdateCaseObservable_FullMethodName             = "/alert_observable_service.AlertObservableService/UpdateCaseObservable"
	AlertObservableService_CreateChildObservableRelation_FullMethodName    = "/alert_observable_service.AlertObservableService/CreateChildObservableRelation"
	AlertObservableService_RecomputeSimilarIncidentsForCase_FullMethodName = "/alert_observable_service.AlertObservableService/RecomputeSimilarIncidentsForCase"
	AlertObservableService_GetAlert_FullMethodName                         = "/alert_observable_service.AlertObservableService/GetAlert"
	AlertObservableService_ListCaseAlerts_FullMethodName                   = "/alert_observable_service.AlertObservableService/ListCaseAlerts"
	AlertObservableService_GetObservable_FullMethodName                    = "/alert_observable_service.AlertObservableService/GetObservable"
	AlertObservableService_ListCaseObservables_FullMethodName              = "/alert_observable_service.AlertObservableService/ListCaseObservables"
	AlertObservableService_ListChildObservables_FullMethodName             = "/alert_observable_service.AlertObservableService/ListChildObservables"
	AlertObservableService_ListSimilarIncidents_FullMethodName             = "/alert_observable_service.AlertObservableService/ListSimilarIncidents"
	AlertObservableService_FindCasesByObservable_FullMethodName            = "/alert_observable_service.AlertObservableService/FindCasesByObservable"
)

// AlertObservableServiceClient is the client API for AlertObservableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertObservableServiceClient interface {
	CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...grpc.CallOption) (*CreateAlertRuleResponse, error)
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error)
	CreateOrGetObservable(ctx context.Context, in *CreateOrGetObservableRequest, opts ...grpc.CallOption) (*CreateOrGetObservableResponse, error)
	LinkObservableToCase(ctx context.Context, in *LinkObservableToCaseRequest, opts ...grpc.CallOption) (*LinkObservableToCaseResponse, error)
	UpdateCaseObservable(ctx context.Context, in *UpdateCaseObservableRequest, opts ...grpc.CallOption) (*UpdateCaseObservableResponse, error)
	CreateChildObservableRelation(ctx context.Context, in *CreateChildObservableRelationRequest, opts ...grpc.CallOption) (*CreateChildObservableRelationResponse, error)
	RecomputeSimilarIncidentsForCase(ctx context.Context, in *RecomputeSimilarIncidentsForCaseRequest, opts ...grpc.CallOption) (*RecomputeSimilarIncidentsForCaseResponse, error)
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertResponse, error)
	ListCaseAlerts(ctx context.Context, in *ListCaseAlertsRequest, opts ...grpc.CallOption) (*ListCaseAlertsResponse, error)
	GetObservable(ctx context.Context, in *GetObservableRequest, opts ...grpc.CallOption) (*GetObservableResponse, error)
	ListCaseObservables(ctx context.Context, in *ListCaseObservablesRequest, opts ...grpc.CallOption) (*ListCaseObservablesResponse, error)
	ListChildObservables(ctx context.Context, in *ListChildObservablesRequest, opts ...grpc.CallOption) (*ListChildObservablesResponse, error)
	ListSimilarIncidents(ctx context.Context, in *ListSimilarIncidentsRequest, opts ...grpc.CallOption) (*ListSimilarIncidentsResponse, error)
	FindCasesByObservable(ctx context.Context, in *FindCasesByObservableRequest, opts ...grpc.CallOption) (*FindCasesByObservableResponse, error)
}

type alertObservableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertObservableServiceClient(cc grpc.ClientConnInterface) AlertObservableServiceClient {
	return &alertObservableServiceClient{cc}
}

func (c *alertObservableServiceClient) CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...grpc.CallOption) (*CreateAlertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertRuleResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_CreateAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) CreateOrGetObservable(ctx context.Context, in *CreateOrGetObservableRequest, opts ...grpc.CallOption) (*CreateOrGetObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrGetObservableResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_CreateOrGetObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) LinkObservableToCase(ctx context.Context, in *LinkObservableToCaseRequest, opts ...grpc.CallOption) (*LinkObservableToCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkObservableToCaseResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_LinkObservableToCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) UpdateCaseObservable(ctx context.Context, in *UpdateCaseObservableRequest, opts ...grpc.CallOption) (*UpdateCaseObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCaseObservableResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_UpdateCaseObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) CreateChildObservableRelation(ctx context.Context, in *CreateChildObservableRelationRequest, opts ...grpc.CallOption) (*CreateChildObservableRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChildObservableRelationResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_CreateChildObservableRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) RecomputeSimilarIncidentsForCase(ctx context.Context, in *RecomputeSimilarIncidentsForCaseRequest, opts ...grpc.CallOption) (*RecomputeSimilarIncidentsForCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecomputeSimilarIncidentsForCaseResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_RecomputeSimilarIncidentsForCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) ListCaseAlerts(ctx context.Context, in *ListCaseAlertsRequest, opts ...grpc.CallOption) (*ListCaseAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCaseAlertsResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_ListCaseAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) GetObservable(ctx context.Context, in *GetObservableRequest, opts ...grpc.CallOption) (*GetObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObservableResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_GetObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) ListCaseObservables(ctx context.Context, in *ListCaseObservablesRequest, opts ...grpc.CallOption) (*ListCaseObservablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCaseObservablesResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_ListCaseObservables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) ListChildObservables(ctx context.Context, in *ListChildObservablesRequest, opts ...grpc.CallOption) (*ListChildObservablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChildObservablesResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_ListChildObservables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) ListSimilarIncidents(ctx context.Context, in *ListSimilarIncidentsRequest, opts ...grpc.CallOption) (*ListSimilarIncidentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSimilarIncidentsResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_ListSimilarIncidents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertObservableServiceClient) FindCasesByObservable(ctx context.Context, in *FindCasesByObservableRequest, opts ...grpc.CallOption) (*FindCasesByObservableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCasesByObservableResponse)
	err := c.cc.Invoke(ctx, AlertObservableService_FindCasesByObservable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertObservableServiceServer is the server API for AlertObservableService service.
// All implementations must embed UnimplementedAlertObservableServiceServer
// for forward compatibility.
type AlertObservableServiceServer interface {
	CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*CreateAlertRuleResponse, error)
	CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error)
	CreateOrGetObservable(context.Context, *CreateOrGetObservableRequest) (*CreateOrGetObservableResponse, error)
	LinkObservableToCase(context.Context, *LinkObservableToCaseRequest) (*LinkObservableToCaseResponse, error)
	UpdateCaseObservable(context.Context, *UpdateCaseObservableRequest) (*UpdateCaseObservableResponse, error)
	CreateChildObservableRelation(context.Context, *CreateChildObservableRelationRequest) (*CreateChildObservableRelationResponse, error)
	RecomputeSimilarIncidentsForCase(context.Context, *RecomputeSimilarIncidentsForCaseRequest) (*RecomputeSimilarIncidentsForCaseResponse, error)
	GetAlert(context.Context, *GetAlertRequest) (*GetAlertResponse, error)
	ListCaseAlerts(context.Context, *ListCaseAlertsRequest) (*ListCaseAlertsResponse, error)
	GetObservable(context.Context, *GetObservableRequest) (*GetObservableResponse, error)
	ListCaseObservables(context.Context, *ListCaseObservablesRequest) (*ListCaseObservablesResponse, error)
	ListChildObservables(context.Context, *ListChildObservablesRequest) (*ListChildObservablesResponse, error)
	ListSimilarIncidents(context.Context, *ListSimilarIncidentsRequest) (*ListSimilarIncidentsResponse, error)
	FindCasesByObservable(context.Context, *FindCasesByObservableRequest) (*FindCasesByObservableResponse, error)
	mustEmbedUnimplementedAlertObservableServiceServer()
}

// UnimplementedAlertObservableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertObservableServiceServer struct{}

func (UnimplementedAlertObservableServiceServer) CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*CreateAlertRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlertRule not implemented")
}
func (UnimplementedAlertObservableServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedAlertObservableServiceServer) CreateOrGetObservable(context.Context, *CreateOrGetObservableRequest) (*CreateOrGetObservableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrGetObservable not implemented")
}
func (UnimplementedAlertObservableServiceServer) LinkObservableToCase(context.Context, *LinkObservableToCaseRequest) (*LinkObservableToCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkObservableToCase not implemented")
}
func (UnimplementedAlertObservableServiceServer) UpdateCaseObservable(context.Context, *UpdateCaseObservableRequest) (*UpdateCaseObservableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCaseObservable not implemented")
}
func (UnimplementedAlertObservableServiceServer) CreateChildObservableRelation(context.Context, *CreateChildObservableRelationRequest) (*CreateChildObservableRelationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChildObservableRelation not implemented")
}
func (UnimplementedAlertObservableServiceServer) RecomputeSimilarIncidentsForCase(context.Context, *RecomputeSimilarIncidentsForCaseRequest) (*RecomputeSimilarIncidentsForCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecomputeSimilarIncidentsForCase not implemented")
}
func (UnimplementedAlertObservableServiceServer) GetAlert(context.Context, *GetAlertRequest) (*GetAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedAlertObservableServiceServer) ListCaseAlerts(context.Context, *ListCaseAlertsRequest) (*ListCaseAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCaseAlerts not implemented")
}
func (UnimplementedAlertObservableServiceServer) GetObservable(context.Context, *GetObservableRequest) (*GetObservableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObservable not implemented")
}
func (UnimplementedAlertObservableServiceServer) ListCaseObservables(context.Context, *ListCaseObservablesRequest) (*ListCaseObservablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCaseObservables not implemented")
}
func (UnimplementedAlertObservableServiceServer) ListChildObservables(context.Context, *ListChildObservablesRequest) (*ListChildObservablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChildObservables not implemented")
}
func (UnimplementedAlertObservableServiceServer) ListSimilarIncidents(context.Context, *ListSimilarIncidentsRequest) (*ListSimilarIncidentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSimilarIncidents not implemented")
}
func (UnimplementedAlertObservableServiceServer) FindCasesByObservable(context.Context, *FindCasesByObservableRequest) (*FindCasesByObservableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCasesByObservable not implemented")
}
func (UnimplementedAlertObservableServiceServer) mustEmbedUnimplementedAlertObservableServiceServer() {
}
func (UnimplementedAlertObservableServiceServer) testEmbeddedByValue() {}

// UnsafeAlertObservableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertObservableServiceServer will
// result in compilation errors.
type UnsafeAlertObservableServiceServer interface {
	mustEmbedUnimplementedAlertObservableServiceServer()
}

func RegisterAlertObservableServiceServer(s grpc.ServiceRegistrar, srv AlertObservableServiceServer) {
	// If the following call panics, it indicates UnimplementedAlertObservableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertObservableService_ServiceDesc, srv)
}

func _AlertObservableService_CreateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).CreateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_CreateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).CreateAlertRule(ctx, req.(*CreateAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_CreateOrGetObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrGetObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).CreateOrGetObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_CreateOrGetObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).CreateOrGetObservable(ctx, req.(*CreateOrGetObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_LinkObservableToCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkObservableToCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).LinkObservableToCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_LinkObservableToCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).LinkObservableToCase(ctx, req.(*LinkObservableToCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_UpdateCaseObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCaseObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).UpdateCaseObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_UpdateCaseObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).UpdateCaseObservable(ctx, req.(*UpdateCaseObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_CreateChildObservableRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChildObservableRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).CreateChildObservableRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_CreateChildObservableRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).CreateChildObservableRelation(ctx, req.(*CreateChildObservableRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_RecomputeSimilarIncidentsForCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecomputeSimilarIncidentsForCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).RecomputeSimilarIncidentsForCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_RecomputeSimilarIncidentsForCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).RecomputeSimilarIncidentsForCase(ctx, req.(*RecomputeSimilarIncidentsForCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_ListCaseAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCaseAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).ListCaseAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_ListCaseAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).ListCaseAlerts(ctx, req.(*ListCaseAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_GetObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).GetObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_GetObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).GetObservable(ctx, req.(*GetObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_ListCaseObservables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCaseObservablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).ListCaseObservables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_ListCaseObservables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).ListCaseObservables(ctx, req.(*ListCaseObservablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_ListChildObservables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChildObservablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).ListChildObservables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_ListChildObservables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).ListChildObservables(ctx, req.(*ListChildObservablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_ListSimilarIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimilarIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).ListSimilarIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_ListSimilarIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).ListSimilarIncidents(ctx, req.(*ListSimilarIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertObservableService_FindCasesByObservable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCasesByObservableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertObservableServiceServer).FindCasesByObservable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertObservableService_FindCasesByObservable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertObservableServiceServer).FindCasesByObservable(ctx, req.(*FindCasesByObservableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertObservableService_ServiceDesc is the grpc.ServiceDesc for AlertObservableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertObservableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alert_observable_service.AlertObservableService",
	HandlerType: (*AlertObservableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlertRule",
			Handler:    _AlertObservableService_CreateAlertRule_Handler,
		},
		{
			MethodName: "CreateAlert",
			Handler:    _AlertObservableService_CreateAlert_Handler,
		},
		{
			MethodName: "CreateOrGetObservable",
			Handler:    _AlertObservableService_CreateOrGetObservable_Handler,
		},
		{
			MethodName: "LinkObservableToCase",
			Handler:    _AlertObservableService_LinkObservableToCase_Handler,
		},
		{
			MethodName: "UpdateCaseObservable",
			Handler:    _AlertObservableService_UpdateCaseObservable_Handler,
		},
		{
			MethodName: "CreateChildObservableRelation",
			Handler:    _AlertObservableService_CreateChildObservableRelation_Handler,
		},
		{
			MethodName: "RecomputeSimilarIncidentsForCase",
			Handler:    _AlertObservableService_RecomputeSimilarIncidentsForCase_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _AlertObservableService_GetAlert_Handler,
		},
		{
			MethodName: "ListCaseAlerts",
			Handler:    _AlertObservableService_ListCaseAlerts_Handler,
		},
		{
			MethodName: "GetObservable",
			Handler:    _AlertObservableService_GetObservable_Handler,
		},
		{
			MethodName: "ListCaseObservables",
			Handler:    _AlertObservableService_ListCaseObservables_Handler,
		},
		{
			MethodName: "ListChildObservables",
			Handler:    _AlertObservableService_ListChildObservables_Handler,
		},
		{
			MethodName: "ListSimilarIncidents",
			Handler:    _AlertObservableService_ListSimilarIncidents_Handler,
		},
		{
			MethodName: "FindCasesByObservable",
			Handler:    _AlertObservableService_FindCasesByObservable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/alert_observable_service.proto",
}
